USE [master]
GO

/****** Object:  Database [DatabaseServices]    Script Date: 07/08/2013 20:50:24 ******/
CREATE DATABASE [DatabaseServices] ON  PRIMARY 
( NAME = N'DatabaseServices', FILENAME = N'F:\SQL\Data\DatabaseServices.mdf' , SIZE = 15311872KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB )
 LOG ON 
( NAME = N'DatabaseServices_log', FILENAME = N'L:\SQL\LOG\DatabaseServices_log.ldf' , SIZE = 973824KB , MAXSIZE = 2048GB , FILEGROWTH = 51200KB )
GO

ALTER DATABASE [DatabaseServices] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DatabaseServices].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DatabaseServices] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DatabaseServices] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DatabaseServices] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DatabaseServices] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DatabaseServices] SET ARITHABORT OFF 
GO

ALTER DATABASE [DatabaseServices] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DatabaseServices] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DatabaseServices] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DatabaseServices] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DatabaseServices] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DatabaseServices] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DatabaseServices] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DatabaseServices] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DatabaseServices] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DatabaseServices] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DatabaseServices] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DatabaseServices] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DatabaseServices] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DatabaseServices] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DatabaseServices] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DatabaseServices] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DatabaseServices] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DatabaseServices] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DatabaseServices] SET  READ_WRITE 
GO

ALTER DATABASE [DatabaseServices] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DatabaseServices] SET  MULTI_USER 
GO

ALTER DATABASE [DatabaseServices] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DatabaseServices] SET DB_CHAINING OFF 
GO


