--  Restore other NBS databases from PROD (AOPSDBSCLSTR02\MCDB) to STAGING (ASTADBS012\MCDB)

--  VM into astadbs012, copy backup file from \\aopsdbsclstr02\B$\AOPSDBSCLSTR02\MCDB to local B(or Z):\temp\

--  For BOWS
DECLARE @BackupFile VARCHAR(255)
SET @BackupFile = 'L:\Backup\BOWS_201004210539.BAK'
RESTORE FILELISTONLY FROM DISK = @BackupFile; 

ALTER DATABASE BOWS SET OffLINE WITH ROLLBACK IMMEDIATE;

RESTORE DATABASE BOWS FROM DISK = @BackupFile WITH REPLACE, STATS = 1,
MOVE 'BOWS_Data' TO 'U:\SQL\DATA\BOWS_Data.mdf',
MOVE 'BOWS_log' TO 'V:\SQL\LOG\BOWS_Log.ldf';


--  For MCDB
DECLARE @BackupFile VARCHAR(255)
SET @BackupFile = 'L:\Backup\MCDB_201004210530.BAK'
RESTORE FILELISTONLY FROM DISK = @BackupFile; 

ALTER DATABASE MCDB SET OFFLINE WITH ROLLBACK IMMEDIATE;

RESTORE DATABASE MCDB FROM DISK = @BackupFile WITH REPLACE, STATS = 1,
MOVE 'MCDB' TO 'U:\SQL\DATA\MCDB.mdf',
MOVE 'FG_MCDB_01' TO 'J:\SQL\DATA\FG_MCDB_01.ndf',
MOVE 'FG_MCDB_02' TO 'K:\SQL\DATA\FG_MCDB_02.ndf',
MOVE 'FG_MCDB_03' TO 'N:\SQL\DATA\FG_MCDB_03.ndf',
MOVE 'FG_MCDB_04' TO 'O:\SQL\DATA\FG_MCDB_04.ndf',
MOVE 'MCDB_log' TO 'V:\SQL\LOG\MCDB_log.ldf';



--  For MCDBStaging
DECLARE @BackupFile VARCHAR(255)
SET @BackupFile = 'L:\Backup\MCDBSTAGING_201004210538.BAK'
RESTORE FILELISTONLY FROM DISK = @BackupFile; 

ALTER DATABASE MCDBStaging SET OFFLINE WITH ROLLBACK IMMEDIATE;

RESTORE DATABASE MCDBStaging FROM DISK = @BackupFile WITH REPLACE, STATS = 1,
MOVE 'MCDBStaging' TO 'U:\SQL\DATA\MCDBStaging.mdf',
MOVE 'FG_MCDBStaging_01' TO 'O:\SQL\DATA\FG_MCDBStaging_01.ndf',
MOVE 'FG_MCDBStaging_02' TO 'U:\SQL\DATA\FG_MCDBStaging_02.ndf',
MOVE 'MCDBStaging_log' TO 'V:\SQL\LOG\MCDBStaging_log.ldf';


--  For ODSStaging
--  drop database odsstaging
DECLARE @BackupFile VARCHAR(255)
SET @BackupFile = 'L:\Backup\ODSSTAGING_201004210540.BAK'
RESTORE FILELISTONLY FROM DISK = @BackupFile; 

--ALTER DATABASE ODSSTAGING SET OnLINE WITH ROLLBACK IMMEDIATE;

RESTORE DATABASE ODSSTAGING FROM DISK = @BackupFile WITH REPLACE, STATS = 1,
MOVE 'ODSStaging_Data' TO 'U:\SQL\DATA\ODSStaging_Data.mdf',
MOVE 'ODSStaging_Data_01' TO 'O:\SQL\DATA\ODSStaging_Data_01.ndf',
MOVE 'ODSStaging_Data_02' TO 'U:\SQL\DATA\ODSStaging_Data_02.ndf',
MOVE 'ODSStaging_log' TO 'V:\SQL\LOG\ODSStaging_log.ldf';

