--  Restore WellnessODS from PROD (AOPSDBSCLSTR03\ODS) to the following environments:
--    DEV (ADEVDBS011\ODS)
--    TEST (ATSTDBS011\ODS)
--    STAGING (ASTADBS011\ODS)


--  For BOWS
DECLARE @BackupFile VARCHAR(255)
SET @BackupFile = 'H:\Temp\BOWS_201004140540.BAK'
RESTORE FILELISTONLY FROM DISK = @BackupFile; 

ALTER DATABASE BOWS SET OffLINE WITH ROLLBACK IMMEDIATE;

RESTORE DATABASE BOWS FROM DISK = @BackupFile WITH REPLACE, STATS = 1,
MOVE 'BOWS_Data' TO 'E:\SQL\DATA\BOWS_Data.mdf',
MOVE 'BOWS_log' TO 'F:\SQL\LOG\BOWS_Log.ldf';


--  For MCDB
DECLARE @BackupFile VARCHAR(255)
SET @BackupFile = 'H:\Temp\MCDB_201004140530.BAK'
RESTORE FILELISTONLY FROM DISK = @BackupFile; 

ALTER DATABASE MCDB SET OFFLINE WITH ROLLBACK IMMEDIATE;

RESTORE DATABASE MCDB FROM DISK = @BackupFile WITH REPLACE, STATS = 1,
MOVE 'MCDB' TO 'g:\SQL\DATA\MCDB.mdf',
MOVE 'FG_MCDB_01' TO 'g:\SQL\DATA\FG_MCDB_01.ndf',
MOVE 'FG_MCDB_02' TO 'g:\SQL\DATA\FG_MCDB_02.ndf',
MOVE 'FG_MCDB_03' TO 'g:\SQL\DATA\FG_MCDB_03.ndf',
MOVE 'FG_MCDB_04' TO 'g:\SQL\DATA\FG_MCDB_04.ndf',
MOVE 'MCDB_log' TO 'h:\SQL\LOG\MCDB_log.ldf';


--  For MCDBStaging
DECLARE @BackupFile VARCHAR(255)
SET @BackupFile = 'H:\Temp\MCDBSTAGING_201004140539.BAK'
RESTORE FILELISTONLY FROM DISK = @BackupFile; 

ALTER DATABASE MCDBStaging SET OFFLINE WITH ROLLBACK IMMEDIATE;

RESTORE DATABASE MCDBStaging FROM DISK = @BackupFile WITH REPLACE, STATS = 1,
MOVE 'MCDBStaging' TO 'g:\SQL\DATA\MCDBStaging.mdf',
MOVE 'FG_MCDBStaging_01' TO 'g:\SQL\DATA\FG_MCDBStaging_01.ndf',
MOVE 'FG_MCDBStaging_02' TO 'g:\SQL\DATA\FG_MCDBStaging_02.ndf',
MOVE 'MCDBStaging_log' TO 'h:\SQL\LOG\MCDBStaging_log.ldf';


--  For ODSStaging
DECLARE @BackupFile VARCHAR(255)
SET @BackupFile = 'H:\Temp\ODSSTAGING_201004140540.BAK'
RESTORE FILELISTONLY FROM DISK = @BackupFile; 

ALTER DATABASE ODSSTAGING SET OFFLINE WITH ROLLBACK IMMEDIATE;

RESTORE DATABASE ODSSTAGING FROM DISK = @BackupFile WITH REPLACE, STATS = 1,
MOVE 'ODSStaging_Data' TO 'g:\SQL\DATA\ODSStaging_Data.mdf',
MOVE 'ODSStaging_Data_01' TO 'g:\SQL\DATA\ODSStaging_Data_01.ndf',
MOVE 'ODSStaging_Data_02' TO 'g:\SQL\DATA\ODSStaging_Data_02.ndf',
MOVE 'ODSStaging_log' TO 'h:\SQL\LOG\ODSStaging_log.ldf';

