/*
  For Dev -
  Script to clean up source data and populate environment specific data in 
  SSIS Config table
  Written by Richard Ding 5/4/2010
*/

USE MCDB;

BEGIN TRANSACTION

--  Remove old data (most likely from production)
TRUNCATE TABLE [dbo].[REF_SSISConfiguration];

-- Add 112 rows to [dbo].[REF_SSISConfiguration]
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (1, N'SSIS_ASA_MCDB_CopyFeedFilesFromBOPS', N'\\e1xia\DEDK_Enhanced_IN\Processed\', N'\Package.Variables[User::DEDKDir].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (2, N'SSIS_ASA_MCDB_CopyFeedFilesFromBOPS', N'ADEVDBS001', N'\Package.Connections[MCDBStaging].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (3, N'SSIS_ASA_MCDB_CopyFeedFilesFromBOPS', N'ADEVDBS001', N'\Package.Connections[MCDB].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (4, N'SSIS_ASA_MCDB_CopyFeedFilesFromBOPS', N'ADEVDBS001', N'\Package.Connections[BOPS].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (5, N'SSIS_ASA_MCDB_CopyFeedFilesFromBOPS', N'Bops', N'\Package.Connections[BOPS].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (7, N'SSIS_ASA_MCDB_CopyFeedFilesFromBOPS', N'MCDB', N'\Package.Connections[MCDB].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (8, N'SSIS_ASA_MCDB_CopyFeedFilesFromBOPS', N'MCDBStaging', N'\Package.Connections[MCDBStaging].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (10, N'SSIS_ASA_MCDB_ExecuteMCDClean', N'0', N'\Package.Variables[User::BatchSize].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (11, N'SSIS_ASA_MCDB_ExecuteMCDClean', N'ADEVDBS001', N'\Package.Connections[MCDB].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (12, N'SSIS_ASA_MCDB_ExecuteMCDClean', N'D:\MCDClean\', N'\Package.Variables[User::ExecutableWorkingPath].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (13, N'SSIS_ASA_MCDB_ExecuteMCDClean', N'MCDB', N'\Package.Connections[MCDB].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (14, N'SSIS_ASA_MCDB_ExecuteMCDClean', N'MCDClean.exe', N'\Package.Variables[User::ExecutableFileName].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (15, N'SSIS_ASA_MCDB_Master', N'ADEVDBS001', N'\Package.Connections[MCDB].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (16, N'SSIS_ASA_MCDB_Master', N'MCDB', N'\Package.Connections[MCDB].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (17, N'SSIS_ASA_MCDB_Master', N'SSIS_ASA_MCDB_PopulateGenericPartnerFiles.dtsx', N'\Package.Variables[User::SubPackageGenericPartnerFiles].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (18, N'SSIS_ASA_MCDB_Master', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailSender].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (19, N'SSIS_ASA_MCDB_Master', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailRecipients].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (20, N'SSIS_ASA_MCDB_Master', N'SSIS_ASA_MCDB_CopyFeedFilesFromBOPS.dtsx', N'\Package.Variables[User::SubPackageCopyBOPSFile].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (21, N'SSIS_ASA_MCDB_Master', N'SSIS_ASA_MCDB_PopulateCAMSubmit_InFiles.dtsx', N'\Package.Variables[User::SubPackageCAMSubmit_In].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (22, N'SSIS_ASA_MCDB_Master', N'SSIS_ASA_MCDB_PopulateCL4AppSend_inFiles.dtsx', N'\Package.Variables[User::SubPackageCL4AppSend_in].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (23, N'SSIS_ASA_MCDB_Master', N'SSIS_ASA_MCDB_PopulateCL4ChgSend_inFiles.dtsx', N'\Package.Variables[User::SubPackageCL4ChgSend_in].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (24, N'SSIS_ASA_MCDB_Master', N'SSIS_ASA_MCDB_PopulateCONSOLDT_INFiles.dtsx', N'\Package.Variables[User::SubPackageCONSOLDT_IN].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (25, N'SSIS_ASA_MCDB_Master', N'SSIS_ASA_MCDB_PopulateCUBSFiles.dtsx', N'\Package.Variables[User::SubPackagePopulateCUBS].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (26, N'SSIS_ASA_MCDB_Master', N'SSIS_ASA_MCDB_PopulateDataFromXI.dtsx', N'\Package.Variables[User::SubPackagePopulateXI].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (27, N'SSIS_ASA_MCDB_Master', N'SSIS_ASA_MCDB_PopulateDEDKENHANCED_INFiles.dtsx', N'\Package.Variables[User::SubPackageDEDKENHANCED_IN].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (28, N'SSIS_ASA_MCDB_Master', N'SSIS_ASA_MCDB_PopulateMPN_INFiles.dtsx', N'\Package.Variables[User::SubPackageMPN_IN].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (29, N'SSIS_ASA_MCDB_Master', N'SSIS_ASA_MCDB_PopulateMYF_INFiles.dtsx', N'\Package.Variables[User::SubPackageMYF_IN].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (30, N'SSIS_ASA_MCDB_PopulateCAMSubmit_InFiles', N'ADEVDBS001', N'\Package.Connections[MCDB].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (31, N'SSIS_ASA_MCDB_PopulateCAMSubmit_InFiles', N'ADEVDBS001', N'\Package.Connections[MCDBStaging].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (32, N'SSIS_ASA_MCDB_PopulateCAMSubmit_InFiles', N'MCDB', N'\Package.Connections[MCDB].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (33, N'SSIS_ASA_MCDB_PopulateCAMSubmit_InFiles', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailSender].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (34, N'SSIS_ASA_MCDB_PopulateCAMSubmit_InFiles', N'MCDBStaging', N'\Package.Connections[MCDBStaging].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (35, N'SSIS_ASA_MCDB_PopulateCAMSubmit_InFiles', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailRecipients].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (36, N'SSIS_ASA_MCDB_PopulateCAMSubmit_InFiles', N'SSIS_ASA_MCDB_ExecuteMCDClean.dtsx', N'\Package.Variables[User::SubPackageCallMCDClean].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (37, N'SSIS_ASA_MCDB_PopulateCAMSubmit_InFiles', N'SSIS_ASA_MCDB_PopulateDataFromBOPS.dtsx', N'\Package.Variables[User::SubPackageLoadBOPS].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (38, N'SSIS_ASA_MCDB_PopulateCL4AppSend_inFiles', N'ADEVDBS001', N'\Package.Connections[MCDB].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (39, N'SSIS_ASA_MCDB_PopulateCL4AppSend_inFiles', N'ADEVDBS001', N'\Package.Connections[MCDBStaging].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (40, N'SSIS_ASA_MCDB_PopulateCL4AppSend_inFiles', N'MCDB', N'\Package.Connections[MCDB].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (41, N'SSIS_ASA_MCDB_PopulateCL4AppSend_inFiles', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailSender].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (42, N'SSIS_ASA_MCDB_PopulateCL4AppSend_inFiles', N'MCDBStaging', N'\Package.Connections[MCDBStaging].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (43, N'SSIS_ASA_MCDB_PopulateCL4AppSend_inFiles', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailRecipients].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (44, N'SSIS_ASA_MCDB_PopulateCL4AppSend_inFiles', N'SSIS_ASA_MCDB_ExecuteMCDClean.dtsx', N'\Package.Variables[User::SubPackageCallMCDClean].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (45, N'SSIS_ASA_MCDB_PopulateCL4AppSend_inFiles', N'SSIS_ASA_MCDB_PopulateDataFromBOPS.dtsx', N'\Package.Variables[User::SubPackageLoadBOPS].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (46, N'SSIS_ASA_MCDB_PopulateCL4ChgSend_inFiles', N'ADEVDBS001', N'\Package.Connections[MCDB].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (47, N'SSIS_ASA_MCDB_PopulateCL4ChgSend_inFiles', N'ADEVDBS001', N'\Package.Connections[MCDBStaging].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (48, N'SSIS_ASA_MCDB_PopulateCL4ChgSend_inFiles', N'MCDB', N'\Package.Connections[MCDB].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (49, N'SSIS_ASA_MCDB_PopulateCL4ChgSend_inFiles', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailSender].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (50, N'SSIS_ASA_MCDB_PopulateCL4ChgSend_inFiles', N'MCDBStaging', N'\Package.Connections[MCDBStaging].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (51, N'SSIS_ASA_MCDB_PopulateCL4ChgSend_inFiles', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailRecipients].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (52, N'SSIS_ASA_MCDB_PopulateCL4ChgSend_inFiles', N'SSIS_ASA_MCDB_ExecuteMCDClean.dtsx', N'\Package.Variables[User::SubPackageCallMCDClean].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (53, N'SSIS_ASA_MCDB_PopulateCL4ChgSend_inFiles', N'SSIS_ASA_MCDB_PopulateDataFromBOPS.dtsx', N'\Package.Variables[User::SubPackageLoadBOPS].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (54, N'SSIS_ASA_MCDB_PopulateCONSOLDT_INFiles', N'ADEVDBS001', N'\Package.Connections[MCDB].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (55, N'SSIS_ASA_MCDB_PopulateCONSOLDT_INFiles', N'ADEVDBS001', N'\Package.Connections[MCDBStaging].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (56, N'SSIS_ASA_MCDB_PopulateCONSOLDT_INFiles', N'MCDB', N'\Package.Connections[MCDB].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (57, N'SSIS_ASA_MCDB_PopulateCONSOLDT_INFiles', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailSender].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (58, N'SSIS_ASA_MCDB_PopulateCONSOLDT_INFiles', N'MCDBStaging', N'\Package.Connections[MCDBStaging].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (59, N'SSIS_ASA_MCDB_PopulateCONSOLDT_INFiles', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailRecipients].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (60, N'SSIS_ASA_MCDB_PopulateCONSOLDT_INFiles', N'SSIS_ASA_MCDB_ExecuteMCDClean.dtsx', N'\Package.Variables[User::SubPackageCallMCDClean].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (61, N'SSIS_ASA_MCDB_PopulateCONSOLDT_INFiles', N'SSIS_ASA_MCDB_PopulateDataFromBOPS.dtsx', N'\Package.Variables[User::SubPackageLoadBOPS].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (62, N'SSIS_ASA_MCDB_PopulateCUBSFiles', N'ADEVDBS001', N'\Package.Connections[MCDB].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (63, N'SSIS_ASA_MCDB_PopulateCUBSFiles', N'ADEVDBS001', N'\Package.Connections[MCDBStaging].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (64, N'SSIS_ASA_MCDB_PopulateCUBSFiles', N'MCDB', N'\Package.Connections[MCDB].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (65, N'SSIS_ASA_MCDB_PopulateCUBSFiles', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailSender].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (66, N'SSIS_ASA_MCDB_PopulateCUBSFiles', N'MCDBStaging', N'\Package.Connections[MCDBStaging].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (67, N'SSIS_ASA_MCDB_PopulateCUBSFiles', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailRecipients].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (68, N'SSIS_ASA_MCDB_PopulateCUBSFiles', N'SSIS_ASA_MCDB_ExecuteMCDClean.dtsx', N'\Package.Variables[User::SubPackageCallMCDClean].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (69, N'SSIS_ASA_MCDB_PopulateDataFromBOPS', N'ADEVDBS001', N'\Package.Connections[BOPS].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (70, N'SSIS_ASA_MCDB_PopulateDataFromBOPS', N'ADEVDBS001', N'\Package.Connections[MCDBStaging].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (71, N'SSIS_ASA_MCDB_PopulateDataFromBOPS', N'bops', N'\Package.Connections[BOPS].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (72, N'SSIS_ASA_MCDB_PopulateDataFromBOPS', N'MCDBStaging', N'\Package.Connections[MCDBStaging].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (73, N'SSIS_ASA_MCDB_PopulateDataFromXI', N'ADEVDBS001', N'\Package.Connections[MCDB].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (74, N'SSIS_ASA_MCDB_PopulateDataFromXI', N'ADEVDBS001', N'\Package.Connections[MCDBStaging].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (75, N'SSIS_ASA_MCDB_PopulateDataFromXI', N'ADEVDBS001', N'\Package.Connections[XI].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (76, N'SSIS_ASA_MCDB_PopulateDataFromXI', N'MCDB', N'\Package.Connections[MCDB].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (77, N'SSIS_ASA_MCDB_PopulateDataFromXI', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailSender].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (78, N'SSIS_ASA_MCDB_PopulateDataFromXI', N'MCDBStaging', N'\Package.Connections[MCDBStaging].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (79, N'SSIS_ASA_MCDB_PopulateDataFromXI', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailRecipients].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (80, N'SSIS_ASA_MCDB_PopulateDataFromXI', N'SSIS_ASA_MCDB_ExecuteMCDClean.dtsx', N'\Package.Variables[User::SubPackageCallMCDClean].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (81, N'SSIS_ASA_MCDB_PopulateDataFromXI', N'XI', N'\Package.Connections[XI].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (82, N'SSIS_ASA_MCDB_PopulateDEDKENHANCED_INFiles', N'ADEVDBS001', N'\Package.Connections[MCDB].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (83, N'SSIS_ASA_MCDB_PopulateDEDKENHANCED_INFiles', N'ADEVDBS001', N'\Package.Connections[MCDBStaging].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (84, N'SSIS_ASA_MCDB_PopulateDEDKENHANCED_INFiles', N'MCDB', N'\Package.Connections[MCDB].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (85, N'SSIS_ASA_MCDB_PopulateDEDKENHANCED_INFiles', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailSender].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (86, N'SSIS_ASA_MCDB_PopulateDEDKENHANCED_INFiles', N'MCDBStaging', N'\Package.Connections[MCDBStaging].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (87, N'SSIS_ASA_MCDB_PopulateDEDKENHANCED_INFiles', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailRecipients].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (88, N'SSIS_ASA_MCDB_PopulateDEDKENHANCED_INFiles', N'SSIS_ASA_MCDB_ExecuteMCDClean.dtsx', N'\Package.Variables[User::SubPackageCallMCDClean].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (89, N'SSIS_ASA_MCDB_PopulateDEDKENHANCED_INFiles', N'SSIS_ASA_MCDB_PopulateDataFromBOPS.dtsx', N'\Package.Variables[User::SubPackageLoadBOPS].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (90, N'SSIS_ASA_MCDB_PopulateGenericPartnerFiles', N'ADEVDBS001', N'\Package.Connections[MCDBStaging].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (91, N'SSIS_ASA_MCDB_PopulateGenericPartnerFiles', N'ADEVDBS001', N'\Package.Connections[MCDB].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (92, N'SSIS_ASA_MCDB_PopulateGenericPartnerFiles', N'MCDB', N'\Package.Connections[MCDB].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (93, N'SSIS_ASA_MCDB_PopulateGenericPartnerFiles', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailSender].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (94, N'SSIS_ASA_MCDB_PopulateGenericPartnerFiles', N'MCDBStaging', N'\Package.Connections[MCDBStaging].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (95, N'SSIS_ASA_MCDB_PopulateGenericPartnerFiles', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailRecipients].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (96, N'SSIS_ASA_MCDB_PopulateGenericPartnerFiles', N'SSIS_ASA_MCDB_ExecuteMCDClean.dtsx', N'\Package.Variables[User::SubPackageCallMCDClean].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (97, N'SSIS_ASA_MCDB_PopulateMPN_INFiles', N'ADEVDBS001', N'\Package.Connections[MCDB].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (98, N'SSIS_ASA_MCDB_PopulateMPN_INFiles', N'ADEVDBS001', N'\Package.Connections[MCDBStaging].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (99, N'SSIS_ASA_MCDB_PopulateMPN_INFiles', N'MCDB', N'\Package.Connections[MCDB].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (100, N'SSIS_ASA_MCDB_PopulateMPN_INFiles', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailSender].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (101, N'SSIS_ASA_MCDB_PopulateMPN_INFiles', N'MCDBStaging', N'\Package.Connections[MCDBStaging].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (102, N'SSIS_ASA_MCDB_PopulateMPN_INFiles', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailRecipients].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (103, N'SSIS_ASA_MCDB_PopulateMPN_INFiles', N'SSIS_ASA_MCDB_ExecuteMCDClean.dtsx', N'\Package.Variables[User::SubPackageCallMCDClean].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (104, N'SSIS_ASA_MCDB_PopulateMPN_INFiles', N'SSIS_ASA_MCDB_PopulateDataFromBOPS.dtsx', N'\Package.Variables[User::SubPackageLoadBOPS].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (105, N'SSIS_ASA_MCDB_PopulateMYF_INFiles', N'ADEVDBS001', N'\Package.Connections[MCDB].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (106, N'SSIS_ASA_MCDB_PopulateMYF_INFiles', N'ADEVDBS001', N'\Package.Connections[MCDBStaging].Properties[ServerName]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (107, N'SSIS_ASA_MCDB_PopulateMYF_INFiles', N'MCDB', N'\Package.Connections[MCDB].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (108, N'SSIS_ASA_MCDB_PopulateMYF_INFiles', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailSender].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (109, N'SSIS_ASA_MCDB_PopulateMYF_INFiles', N'MCDBStaging', N'\Package.Connections[MCDBStaging].Properties[InitialCatalog]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (110, N'SSIS_ASA_MCDB_PopulateMYF_INFiles', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailRecipients].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (111, N'SSIS_ASA_MCDB_PopulateMYF_INFiles', N'SSIS_ASA_MCDB_ExecuteMCDClean.dtsx', N'\Package.Variables[User::SubPackageCallMCDClean].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (112, N'SSIS_ASA_MCDB_PopulateMYF_INFiles', N'SSIS_ASA_MCDB_PopulateDataFromBOPS.dtsx', N'\Package.Variables[User::SubPackageLoadBOPS].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (113, N'SSIS_ASA_MCDB_CopyFeedFilesFromBOPS', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailSender].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);
INSERT INTO [dbo].[REF_SSISConfiguration] ([SSISConfiguration_id], [ConfigurationFilter], [ConfiguredValue], [PackagePath], [ConfiguredValueType], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (114, N'SSIS_ASA_MCDB_CopyFeedFilesFromBOPS', N'ASABUSSYSTESTANDRELEASE@amsa.com', N'\Package.Variables[User::EmailRecipients].Properties[Value]', N'String', 'Y', 'InitialRelease', '2009-06-02 00:00:00.000', NULL, NULL);

COMMIT TRANSACTION
