USE [Filestaging]; CREATE USER [AMSA\dgrigorjev] FROM LOGIN [AMSA\dgrigorjev] WITH DEFAULT_SCHEMA = [dbo];
USE [Filestaging]; CREATE USER [AMSA\ProdDBA] FROM LOGIN [AMSA\ProdDBA];
USE [Filestaging]; CREATE USER [amsa\sql_dev_reader] FROM LOGIN [amsa\sql_dev_reader];
USE [Filestaging]; CREATE USER [AMSA\SQL_PRD_FileStaging_Read] FROM LOGIN [AMSA\SQL_PRD_FileStaging_Read];
USE [Filestaging]; CREATE USER [amsa\SQL_STA_Filestaging_Write] FROM LOGIN [amsa\SQL_STA_Filestaging_Write];
USE [Filestaging]; CREATE USER [AMSA\SQL_STA_Reader] FROM LOGIN [AMSA\SQL_STA_Reader];
USE [Filestaging]; CREATE USER [AMSA\sql_tst_reader] FROM LOGIN [AMSA\sql_tst_reader];
USE [Filestaging]; CREATE USER [AMSA\svdevserviceadapter] FROM LOGIN [AMSA\svdevserviceadapter] WITH DEFAULT_SCHEMA = [AMSA\svdevserviceadapter];
USE [Filestaging]; CREATE USER [AMSA\svprodserviceadapter] FROM LOGIN [AMSA\svprodserviceadapter] WITH DEFAULT_SCHEMA = [dbo];
USE [Filestaging]; CREATE USER [AMSA\SvProdSSISExecFisma] FROM LOGIN [AMSA\SvProdSSISExecFisma] WITH DEFAULT_SCHEMA = [dbo];
USE [Filestaging]; CREATE USER [AMSA\svstaserviceadapter] FROM LOGIN [AMSA\svstaserviceadapter] WITH DEFAULT_SCHEMA = [dbo];
USE [Filestaging]; CREATE USER [AMSA\SvStaSSISExecFisma] FROM LOGIN [AMSA\SvStaSSISExecFisma] WITH DEFAULT_SCHEMA = [dbo];
USE [Filestaging]; CREATE USER [AMSA\twhite] FROM LOGIN [AMSA\twhite] WITH DEFAULT_SCHEMA = [dbo];
USE [Filestaging]; CREATE USER [DBTKUser] FOR LOGIN [DBTKUser] WITH DEFAULT_SCHEMA = [dbo];

--
--
EXEC dbo.sp_addsrvrolemember 'AMSA\SQL Cluster STA Server Service Group', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\SQL Cluster STA Agent Service Group', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\ProdDBA', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\DLake', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\TTrent', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svStaWinCluster', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'SvStaMonOSS', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\ezhang', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\azerilli', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\SvStaSSISExecFisma', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'DBTKUser', 'bulkadmin';
EXEC [Filestaging].dbo.sp_addrolemember 'db_owner', 'DBTKUser';
EXEC [Filestaging].dbo.sp_addrolemember 'db_owner', 'AMSA\dgrigorjev';
EXEC [Filestaging].dbo.sp_addrolemember 'db_owner', 'AMSA\twhite';
EXEC [Filestaging].dbo.sp_addrolemember 'db_datareader', 'AMSA\svprodserviceadapter';
EXEC [Filestaging].dbo.sp_addrolemember 'db_datareader', 'AMSA\SQL_PRD_FileStaging_Read';
EXEC [Filestaging].dbo.sp_addrolemember 'db_datareader', 'amsa\sql_dev_reader';
EXEC [Filestaging].dbo.sp_addrolemember 'db_datareader', 'AMSA\sql_tst_reader';
EXEC [Filestaging].dbo.sp_addrolemember 'db_datareader', 'AMSA\svdevserviceadapter';
EXEC [Filestaging].dbo.sp_addrolemember 'db_datareader', 'AMSA\svstaserviceadapter';
EXEC [Filestaging].dbo.sp_addrolemember 'db_datawriter', 'AMSA\svprodserviceadapter';
EXEC [Filestaging].dbo.sp_addrolemember 'db_datawriter', 'amsa\SQL_STA_Filestaging_Write';
EXEC [Filestaging].dbo.sp_addrolemember 'db_datawriter', 'AMSA\svdevserviceadapter';
EXEC [Filestaging].dbo.sp_addrolemember 'db_datawriter', 'AMSA\svstaserviceadapter';

USE master; GRANT ADMINISTER BULK OPERATIONS TO [AMSA\SvStaSSISExecFisma];
USE master; GRANT ADMINISTER BULK OPERATIONS TO [DBTKUser];
--
USE master; GRANT CONNECT SQL TO [AMSA\azerilli];
USE master; GRANT CONNECT SQL TO [AMSA\bdanrel];
USE master; GRANT CONNECT SQL TO [AMSA\DLake];
USE master; GRANT CONNECT SQL TO [AMSA\ezhang];
USE master; GRANT CONNECT SQL TO [AMSA\hkabir];
USE master; GRANT CONNECT SQL TO [AMSA\ProdDBA];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Agent Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Full Text Search Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Server Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\sql_dev_reader];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_STA_Filestaging_Write];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_STA_Reader];
USE master; GRANT CONNECT SQL TO [AMSA\sql_tst_reader];
USE master; GRANT CONNECT SQL TO [AMSA\svstacontactvalidate];
USE master; GRANT CONNECT SQL TO [AMSA\svstaLoan];
USE master; GRANT CONNECT SQL TO [AMSA\svstaPerson];
USE master; GRANT CONNECT SQL TO [AMSA\svstaRefData];
USE master; GRANT CONNECT SQL TO [AMSA\svstaserviceadapter];
USE master; GRANT CONNECT SQL TO [AMSA\SvStaSSISExecFisma];
USE master; GRANT CONNECT SQL TO [AMSA\svStaWinCluster];
USE master; GRANT CONNECT SQL TO [AMSA\TTrent];
--
USE master; GRANT CONNECT SQL TO [DBTKUser];
USE master; GRANT CONNECT SQL TO [NT AUTHORITY\SYSTEM];
USE master; GRANT CONNECT SQL TO [SvStaMonOSS];
USE master; GRANT CONNECT SQL TO [teamworks];
USE master; GRANT CONNECT SQL TO [TempLinkedServerUser];
USE master; GRANT VIEW ANY DATABASE TO [public];
USE [Filestaging]; GRANT ALTER TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT ALTER ON SCHEMA::dbo TO [AMSA\SvProdSSISExecFisma];
USE [Filestaging]; GRANT ALTER ON SCHEMA::dbo TO [AMSA\SvStaSSISExecFisma];
USE [Filestaging]; GRANT ALTER ANY APPLICATION ROLE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT ALTER ANY ASSEMBLY TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT ALTER ANY ASYMMETRIC KEY TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT ALTER ANY CERTIFICATE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT ALTER ANY CONTRACT TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT ALTER ANY DATABASE DDL TRIGGER TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT ALTER ANY DATABASE EVENT NOTIFICATION TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT ALTER ANY DATASPACE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT ALTER ANY FULLTEXT CATALOG TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT ALTER ANY MESSAGE TYPE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT ALTER ANY REMOTE SERVICE BINDING TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT ALTER ANY ROLE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT ALTER ANY ROUTE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT ALTER ANY SCHEMA TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT ALTER ANY SERVICE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT ALTER ANY SYMMETRIC KEY TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT ALTER ANY USER TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT AUTHENTICATE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT BACKUP DATABASE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT BACKUP LOG TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CHECKPOINT TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CONNECT TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CONNECT TO [AMSA\ProdDBA];
USE [Filestaging]; GRANT CONNECT TO [amsa\sql_dev_reader];
USE [Filestaging]; GRANT CONNECT TO [AMSA\SQL_PRD_FileStaging_Read];
USE [Filestaging]; GRANT CONNECT TO [amsa\SQL_STA_Filestaging_Write];
USE [Filestaging]; GRANT CONNECT TO [AMSA\SQL_STA_Reader];
USE [Filestaging]; GRANT CONNECT TO [AMSA\sql_tst_reader];
USE [Filestaging]; GRANT CONNECT TO [AMSA\svdevserviceadapter];
USE [Filestaging]; GRANT CONNECT TO [AMSA\svprodserviceadapter];
USE [Filestaging]; GRANT CONNECT TO [AMSA\SvProdSSISExecFisma];
USE [Filestaging]; GRANT CONNECT TO [AMSA\svstaserviceadapter];
USE [Filestaging]; GRANT CONNECT TO [AMSA\SvStaSSISExecFisma];
USE [Filestaging]; GRANT CONNECT TO [AMSA\twhite];
--
USE [Filestaging]; GRANT CONNECT TO [DBTKUser];
USE [Filestaging]; GRANT CONNECT REPLICATION TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CONTROL TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE AGGREGATE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE ASSEMBLY TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE ASYMMETRIC KEY TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE CERTIFICATE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE CONTRACT TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE DATABASE DDL EVENT NOTIFICATION TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE DEFAULT TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE FULLTEXT CATALOG TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE FUNCTION TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE MESSAGE TYPE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE PROCEDURE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE QUEUE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE REMOTE SERVICE BINDING TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE ROLE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE ROUTE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE RULE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE SCHEMA TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE SERVICE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE SYMMETRIC KEY TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE SYNONYM TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE TABLE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE TYPE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE VIEW TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT CREATE XML SCHEMA COLLECTION TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT DELETE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT DELETE ON SCHEMA::dbo TO [AMSA\SvProdSSISExecFisma];
USE [Filestaging]; GRANT DELETE ON SCHEMA::dbo TO [AMSA\SvStaSSISExecFisma];
USE [Filestaging]; GRANT EXECUTE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT EXECUTE ON SCHEMA::dbo TO [AMSA\SvProdSSISExecFisma];
USE [Filestaging]; GRANT EXECUTE ON SCHEMA::dbo TO [AMSA\SvStaSSISExecFisma];
USE [Filestaging]; GRANT EXECUTE ON dbo.fssp_LoadXMLRecordToTarget TO [AMSA\svdevserviceadapter];
USE [Filestaging]; GRANT EXECUTE ON dbo.fssp_LoadXMLRecordToTarget TO [AMSA\svprodserviceadapter];
USE [Filestaging]; GRANT EXECUTE ON dbo.fssp_LoadXMLRecordToTarget TO [AMSA\svstaserviceadapter];
USE [Filestaging]; GRANT EXECUTE ON dbo.fssp_SetLoadedXMLRecordStatus TO [AMSA\svdevserviceadapter];
USE [Filestaging]; GRANT EXECUTE ON dbo.fssp_SetLoadedXMLRecordStatus TO [AMSA\svprodserviceadapter];
USE [Filestaging]; GRANT EXECUTE ON dbo.fssp_SetLoadedXMLRecordStatus TO [AMSA\svstaserviceadapter];
USE [Filestaging]; GRANT INSERT TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT INSERT ON SCHEMA::dbo TO [AMSA\SvProdSSISExecFisma];
USE [Filestaging]; GRANT INSERT ON SCHEMA::dbo TO [AMSA\SvStaSSISExecFisma];
USE [Filestaging]; GRANT REFERENCES TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT SELECT TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT SELECT ON SCHEMA::dbo TO [AMSA\SvProdSSISExecFisma];
USE [Filestaging]; GRANT SELECT ON SCHEMA::dbo TO [AMSA\SvStaSSISExecFisma];
USE [Filestaging]; GRANT SELECT ON sys.all_columns TO [public];
USE [Filestaging]; GRANT SELECT ON sys.all_objects TO [public];
USE [Filestaging]; GRANT SELECT ON sys.all_parameters TO [public];
USE [Filestaging]; GRANT SELECT ON sys.all_sql_modules TO [public];
USE [Filestaging]; GRANT SELECT ON sys.all_views TO [public];
USE [Filestaging]; GRANT SELECT ON sys.allocation_units TO [public];
USE [Filestaging]; GRANT SELECT ON sys.assemblies TO [public];
USE [Filestaging]; GRANT SELECT ON sys.assembly_files TO [public];
USE [Filestaging]; GRANT SELECT ON sys.assembly_modules TO [public];
USE [Filestaging]; GRANT SELECT ON sys.assembly_references TO [public];
USE [Filestaging]; GRANT SELECT ON sys.assembly_types TO [public];
USE [Filestaging]; GRANT SELECT ON sys.asymmetric_keys TO [public];
USE [Filestaging]; GRANT SELECT ON sys.certificates TO [public];
USE [Filestaging]; GRANT SELECT ON sys.check_constraints TO [public];
USE [Filestaging]; GRANT SELECT ON sys.column_type_usages TO [public];
USE [Filestaging]; GRANT SELECT ON sys.column_xml_schema_collection_usages TO [public];
USE [Filestaging]; GRANT SELECT ON sys.columns TO [public];
USE [Filestaging]; GRANT SELECT ON sys.computed_columns TO [public];
USE [Filestaging]; GRANT SELECT ON sys.conversation_endpoints TO [public];
USE [Filestaging]; GRANT SELECT ON sys.conversation_groups TO [public];
USE [Filestaging]; GRANT SELECT ON sys.crypt_properties TO [public];
USE [Filestaging]; GRANT SELECT ON sys.data_spaces TO [public];
USE [Filestaging]; GRANT SELECT ON sys.database_files TO [public];
USE [Filestaging]; GRANT SELECT ON sys.database_permissions TO [public];
USE [Filestaging]; GRANT SELECT ON sys.database_principal_aliases TO [public];
USE [Filestaging]; GRANT SELECT ON sys.database_principals TO [public];
USE [Filestaging]; GRANT SELECT ON sys.database_role_members TO [public];
USE [Filestaging]; GRANT SELECT ON sys.default_constraints TO [public];
USE [Filestaging]; GRANT SELECT ON sys.destination_data_spaces TO [public];
USE [Filestaging]; GRANT SELECT ON sys.event_notifications TO [public];
USE [Filestaging]; GRANT SELECT ON sys.events TO [public];
USE [Filestaging]; GRANT SELECT ON sys.extended_procedures TO [public];
USE [Filestaging]; GRANT SELECT ON sys.extended_properties TO [public];
USE [Filestaging]; GRANT SELECT ON sys.filegroups TO [public];
USE [Filestaging]; GRANT SELECT ON sys.foreign_key_columns TO [public];
USE [Filestaging]; GRANT SELECT ON sys.foreign_keys TO [public];
USE [Filestaging]; GRANT SELECT ON sys.fulltext_catalogs TO [public];
USE [Filestaging]; GRANT SELECT ON sys.fulltext_index_catalog_usages TO [public];
USE [Filestaging]; GRANT SELECT ON sys.fulltext_index_columns TO [public];
USE [Filestaging]; GRANT SELECT ON sys.fulltext_indexes TO [public];
USE [Filestaging]; GRANT SELECT ON sys.identity_columns TO [public];
USE [Filestaging]; GRANT SELECT ON sys.index_columns TO [public];
USE [Filestaging]; GRANT SELECT ON sys.indexes TO [public];
USE [Filestaging]; GRANT SELECT ON sys.internal_tables TO [public];
USE [Filestaging]; GRANT SELECT ON sys.key_constraints TO [public];
USE [Filestaging]; GRANT SELECT ON sys.key_encryptions TO [public];
USE [Filestaging]; GRANT SELECT ON sys.message_type_xml_schema_collection_usages TO [public];
USE [Filestaging]; GRANT SELECT ON sys.module_assembly_usages TO [public];
USE [Filestaging]; GRANT SELECT ON sys.numbered_procedure_parameters TO [public];
USE [Filestaging]; GRANT SELECT ON sys.numbered_procedures TO [public];
USE [Filestaging]; GRANT SELECT ON sys.objects TO [public];
USE [Filestaging]; GRANT SELECT ON sys.parameter_type_usages TO [public];
USE [Filestaging]; GRANT SELECT ON sys.parameter_xml_schema_collection_usages TO [public];
USE [Filestaging]; GRANT SELECT ON sys.parameters TO [public];
USE [Filestaging]; GRANT SELECT ON sys.partition_functions TO [public];
USE [Filestaging]; GRANT SELECT ON sys.partition_parameters TO [public];
USE [Filestaging]; GRANT SELECT ON sys.partition_range_values TO [public];
USE [Filestaging]; GRANT SELECT ON sys.partition_schemes TO [public];
USE [Filestaging]; GRANT SELECT ON sys.partitions TO [public];
USE [Filestaging]; GRANT SELECT ON sys.plan_guides TO [public];
USE [Filestaging]; GRANT SELECT ON sys.procedures TO [public];
USE [Filestaging]; GRANT SELECT ON sys.remote_service_bindings TO [public];
USE [Filestaging]; GRANT SELECT ON sys.routes TO [public];
USE [Filestaging]; GRANT SELECT ON sys.schemas TO [public];
USE [Filestaging]; GRANT SELECT ON sys.service_contract_message_usages TO [public];
USE [Filestaging]; GRANT SELECT ON sys.service_contract_usages TO [public];
USE [Filestaging]; GRANT SELECT ON sys.service_contracts TO [public];
USE [Filestaging]; GRANT SELECT ON sys.service_message_types TO [public];
USE [Filestaging]; GRANT SELECT ON sys.service_queue_usages TO [public];
USE [Filestaging]; GRANT SELECT ON sys.service_queues TO [public];
USE [Filestaging]; GRANT SELECT ON sys.services TO [public];
USE [Filestaging]; GRANT SELECT ON sys.sql_dependencies TO [public];
USE [Filestaging]; GRANT SELECT ON sys.sql_modules TO [public];
USE [Filestaging]; GRANT SELECT ON sys.stats TO [public];
USE [Filestaging]; GRANT SELECT ON sys.stats_columns TO [public];
USE [Filestaging]; GRANT SELECT ON sys.symmetric_keys TO [public];
USE [Filestaging]; GRANT SELECT ON sys.synonyms TO [public];
USE [Filestaging]; GRANT SELECT ON sys.syscolumns TO [public];
USE [Filestaging]; GRANT SELECT ON sys.syscomments TO [public];
USE [Filestaging]; GRANT SELECT ON sys.sysconstraints TO [public];
USE [Filestaging]; GRANT SELECT ON sys.sysdepends TO [public];
USE [Filestaging]; GRANT SELECT ON sys.sysfilegroups TO [public];
USE [Filestaging]; GRANT SELECT ON sys.sysfiles TO [public];
USE [Filestaging]; GRANT SELECT ON sys.sysforeignkeys TO [public];
USE [Filestaging]; GRANT SELECT ON sys.sysfulltextcatalogs TO [public];
USE [Filestaging]; GRANT SELECT ON sys.sysindexes TO [public];
USE [Filestaging]; GRANT SELECT ON sys.sysindexkeys TO [public];
USE [Filestaging]; GRANT SELECT ON sys.sysmembers TO [public];
USE [Filestaging]; GRANT SELECT ON sys.sysobjects TO [public];
USE [Filestaging]; GRANT SELECT ON sys.syspermissions TO [public];
USE [Filestaging]; GRANT SELECT ON sys.sysprotects TO [public];
USE [Filestaging]; GRANT SELECT ON sys.sysreferences TO [public];
USE [Filestaging]; GRANT SELECT ON sys.syssegments TO [public];
USE [Filestaging]; GRANT SELECT ON sys.system_columns TO [public];
USE [Filestaging]; GRANT SELECT ON sys.system_objects TO [public];
USE [Filestaging]; GRANT SELECT ON sys.system_parameters TO [public];
USE [Filestaging]; GRANT SELECT ON sys.system_sql_modules TO [public];
USE [Filestaging]; GRANT SELECT ON sys.system_views TO [public];
USE [Filestaging]; GRANT SELECT ON sys.systypes TO [public];
USE [Filestaging]; GRANT SELECT ON sys.sysusers TO [public];
USE [Filestaging]; GRANT SELECT ON sys.tables TO [public];
USE [Filestaging]; GRANT SELECT ON sys.transmission_queue TO [public];
USE [Filestaging]; GRANT SELECT ON sys.trigger_events TO [public];
USE [Filestaging]; GRANT SELECT ON sys.triggers TO [public];
USE [Filestaging]; GRANT SELECT ON sys.type_assembly_usages TO [public];
USE [Filestaging]; GRANT SELECT ON sys.types TO [public];
USE [Filestaging]; GRANT SELECT ON sys.views TO [public];
USE [Filestaging]; GRANT SELECT ON sys.xml_indexes TO [public];
USE [Filestaging]; GRANT SELECT ON sys.xml_schema_attributes TO [public];
USE [Filestaging]; GRANT SELECT ON sys.xml_schema_collections TO [public];
USE [Filestaging]; GRANT SELECT ON sys.xml_schema_component_placements TO [public];
USE [Filestaging]; GRANT SELECT ON sys.xml_schema_components TO [public];
USE [Filestaging]; GRANT SELECT ON sys.xml_schema_elements TO [public];
USE [Filestaging]; GRANT SELECT ON sys.xml_schema_facets TO [public];
USE [Filestaging]; GRANT SELECT ON sys.xml_schema_model_groups TO [public];
USE [Filestaging]; GRANT SELECT ON sys.xml_schema_namespaces TO [public];
USE [Filestaging]; GRANT SELECT ON sys.xml_schema_types TO [public];
USE [Filestaging]; GRANT SELECT ON sys.xml_schema_wildcard_namespaces TO [public];
USE [Filestaging]; GRANT SELECT ON sys.xml_schema_wildcards TO [public];
USE [Filestaging]; GRANT SHOWPLAN TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT SUBSCRIBE QUERY NOTIFICATIONS TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT TAKE OWNERSHIP TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT UPDATE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT UPDATE ON SCHEMA::dbo TO [AMSA\SvProdSSISExecFisma];
USE [Filestaging]; GRANT UPDATE ON SCHEMA::dbo TO [AMSA\SvStaSSISExecFisma];
USE [Filestaging]; GRANT VIEW DATABASE STATE TO [AMSA\dgrigorjev];
USE [Filestaging]; GRANT VIEW DEFINITION TO [AMSA\dgrigorjev];

-------------------------------------------------------------------------------------------------------

USE [WellnessODS]; CREATE USER [AMSA\bdanrel] FROM LOGIN [AMSA\bdanrel] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\dgrigorjev] FROM LOGIN [AMSA\dgrigorjev] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\hkabir] FROM LOGIN [AMSA\hkabir] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\SAS Server Users] FROM LOGIN [AMSA\SAS Server Users];
USE [WellnessODS]; CREATE USER [amsa\sql_dev_reader] FROM LOGIN [amsa\sql_dev_reader];
USE [WellnessODS]; CREATE USER [AMSA\SQL_STA_Reader] FROM LOGIN [AMSA\SQL_STA_Reader];
USE [WellnessODS]; CREATE USER [AMSA\sql_tst_reader] FROM LOGIN [AMSA\sql_tst_reader];
USE [WellnessODS]; CREATE USER [AMSA\svdevcontactvalidate] FROM LOGIN [AMSA\svdevcontactvalidate] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\svdevLoan] FROM LOGIN [AMSA\svdevLoan] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\svdevperson] FROM LOGIN [AMSA\svdevperson] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\svdevRefData] FROM LOGIN [AMSA\svdevRefData] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\svprodcontactvalidat] FROM LOGIN [AMSA\svprodcontactvalidat] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\svprodLoan] FROM LOGIN [AMSA\svprodLoan] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\svprodperson] FROM LOGIN [AMSA\svprodperson] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\svprodRefData] FROM LOGIN [AMSA\svprodRefData] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\svstacontactvalidate] FROM LOGIN [AMSA\svstacontactvalidate] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\svstaLoan] FROM LOGIN [AMSA\svstaLoan] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\svstaPerson] FROM LOGIN [AMSA\svstaPerson] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\svstaRefData] FROM LOGIN [AMSA\svstaRefData] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\twhite] FROM LOGIN [AMSA\twhite] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [DBTKUser] FOR LOGIN [DBTKUser] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [teamworks] FOR LOGIN [teamworks] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [TempLinkedServerUser] FOR LOGIN [TempLinkedServerUser] WITH DEFAULT_SCHEMA = [dbo];

--
--
EXEC dbo.sp_addsrvrolemember 'AMSA\SQL Cluster STA Server Service Group', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\SQL Cluster STA Agent Service Group', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\ProdDBA', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\DLake', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\TTrent', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svStaWinCluster', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'SvStaMonOSS', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\ezhang', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\azerilli', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\SvStaSSISExecFisma', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'DBTKUser', 'bulkadmin';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_owner', 'AMSA\dgrigorjev';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_owner', 'DBTKUser';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_owner', 'teamworks';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_owner', 'AMSA\twhite';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_owner', 'AMSA\bdanrel';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_owner', 'AMSA\hkabir';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'TempLinkedServerUser';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\SAS Server Users';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svprodLoan';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svprodperson';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svprodRefData';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'amsa\sql_dev_reader';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\SQL_STA_Reader';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\sql_tst_reader';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svprodcontactvalidat';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svdevcontactvalidate';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svdevLoan';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svdevperson';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svdevRefData';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svstacontactvalidate';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svstaLoan';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svstaPerson';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svstaRefData';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datawriter', 'AMSA\svprodLoan';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datawriter', 'AMSA\svprodperson';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datawriter', 'AMSA\svdevLoan';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datawriter', 'AMSA\svdevperson';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datawriter', 'AMSA\svstaLoan';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datawriter', 'AMSA\svstaPerson';

USE master; GRANT ADMINISTER BULK OPERATIONS TO [AMSA\SvStaSSISExecFisma];
USE master; GRANT ADMINISTER BULK OPERATIONS TO [DBTKUser];
--
USE master; GRANT CONNECT SQL TO [AMSA\azerilli];
USE master; GRANT CONNECT SQL TO [AMSA\bdanrel];
USE master; GRANT CONNECT SQL TO [AMSA\DLake];
USE master; GRANT CONNECT SQL TO [AMSA\ezhang];
USE master; GRANT CONNECT SQL TO [AMSA\hkabir];
USE master; GRANT CONNECT SQL TO [AMSA\ProdDBA];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Agent Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Full Text Search Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Server Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\sql_dev_reader];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_STA_Filestaging_Write];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_STA_Reader];
USE master; GRANT CONNECT SQL TO [AMSA\sql_tst_reader];
USE master; GRANT CONNECT SQL TO [AMSA\svstacontactvalidate];
USE master; GRANT CONNECT SQL TO [AMSA\svstaLoan];
USE master; GRANT CONNECT SQL TO [AMSA\svstaPerson];
USE master; GRANT CONNECT SQL TO [AMSA\svstaRefData];
USE master; GRANT CONNECT SQL TO [AMSA\svstaserviceadapter];
USE master; GRANT CONNECT SQL TO [AMSA\SvStaSSISExecFisma];
USE master; GRANT CONNECT SQL TO [AMSA\svStaWinCluster];
USE master; GRANT CONNECT SQL TO [AMSA\TTrent];
--
USE master; GRANT CONNECT SQL TO [DBTKUser];
USE master; GRANT CONNECT SQL TO [NT AUTHORITY\SYSTEM];
USE master; GRANT CONNECT SQL TO [SvStaMonOSS];
USE master; GRANT CONNECT SQL TO [teamworks];
USE master; GRANT CONNECT SQL TO [TempLinkedServerUser];
USE master; GRANT VIEW ANY DATABASE TO [public];
USE [WellnessODS]; GRANT ALTER ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\bdanrel];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\dgrigorjev];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\hkabir];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\SAS Server Users];
USE [WellnessODS]; GRANT CONNECT TO [amsa\sql_dev_reader];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\SQL_STA_Reader];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\sql_tst_reader];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svdevcontactvalidate];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svdevLoan];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svdevperson];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svdevRefData];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svprodcontactvalidat];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svprodLoan];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svprodperson];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svprodRefData];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svstacontactvalidate];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svstaLoan];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svstaPerson];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svstaRefData];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\twhite];
--
USE [WellnessODS]; GRANT CONNECT TO [DBTKUser];
USE [WellnessODS]; GRANT CONNECT TO [teamworks];
USE [WellnessODS]; GRANT CONNECT TO [TempLinkedServerUser];
USE [WellnessODS]; GRANT CONTROL ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE DEFAULT TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE FUNCTION TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE PROCEDURE TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE ROLE TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE RULE TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE SCHEMA TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE TABLE TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE TYPE TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE VIEW TO [DBTKUser];
USE [WellnessODS]; GRANT DELETE ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT EXECUTE ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT EXECUTE ON SCHEMA::dbo TO [teamworks];
USE [WellnessODS]; GRANT INSERT ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT SELECT ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT SELECT ON sys.all_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.all_objects TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.all_parameters TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.all_sql_modules TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.all_views TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.allocation_units TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.assemblies TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.assembly_files TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.assembly_modules TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.assembly_references TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.assembly_types TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.asymmetric_keys TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.certificates TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.check_constraints TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.column_type_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.column_xml_schema_collection_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.computed_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.conversation_endpoints TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.conversation_groups TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.crypt_properties TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.data_spaces TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.database_files TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.database_permissions TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.database_principal_aliases TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.database_principals TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.database_role_members TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.default_constraints TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.destination_data_spaces TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.event_notifications TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.events TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.extended_procedures TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.extended_properties TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.filegroups TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.foreign_key_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.foreign_keys TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.fulltext_catalogs TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.fulltext_index_catalog_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.fulltext_index_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.fulltext_indexes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.identity_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.index_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.indexes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.internal_tables TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.key_constraints TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.key_encryptions TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.message_type_xml_schema_collection_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.module_assembly_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.numbered_procedure_parameters TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.numbered_procedures TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.objects TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.parameter_type_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.parameter_xml_schema_collection_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.parameters TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.partition_functions TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.partition_parameters TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.partition_range_values TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.partition_schemes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.partitions TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.plan_guides TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.procedures TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.remote_service_bindings TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.routes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.schemas TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.service_contract_message_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.service_contract_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.service_contracts TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.service_message_types TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.service_queue_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.service_queues TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.services TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sql_dependencies TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sql_modules TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.stats TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.stats_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.symmetric_keys TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.synonyms TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.syscolumns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.syscomments TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysconstraints TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysdepends TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysfilegroups TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysfiles TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysforeignkeys TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysfulltextcatalogs TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysindexes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysindexkeys TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysmembers TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysobjects TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.syspermissions TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysprotects TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysreferences TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.syssegments TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.system_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.system_objects TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.system_parameters TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.system_sql_modules TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.system_views TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.systypes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysusers TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.tables TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.transmission_queue TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.trigger_events TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.triggers TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.type_assembly_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.types TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.views TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_indexes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_attributes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_collections TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_component_placements TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_components TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_elements TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_facets TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_model_groups TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_namespaces TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_types TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_wildcard_namespaces TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_wildcards TO [public];
USE [WellnessODS]; GRANT UPDATE ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT VIEW DEFINITION TO [AMSA\SQL_STA_Reader];
USE [WellnessODS]; GRANT VIEW DEFINITION TO [DBTKUser];