USE [WellnessODS]; CREATE USER [AMSA\SAS Server Users] FROM LOGIN [AMSA\SAS Server Users];
USE [WellnessODS]; CREATE USER [AMSA\SQL_DEV_Reader] FROM LOGIN [AMSA\SQL_DEV_Reader];
USE [WellnessODS]; CREATE USER [AMSA\SQL_TST_Reader] FROM LOGIN [AMSA\SQL_TST_Reader];
USE [WellnessODS]; CREATE USER [AMSA\svtstcontactvalidate] FROM LOGIN [AMSA\svtstcontactvalidate] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\svtstLoan] FROM LOGIN [AMSA\svtstLoan] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\svtstperson] FROM LOGIN [AMSA\svtstperson] WITH DEFAULT_SCHEMA = [AMSA\svtstperson];
USE [WellnessODS]; CREATE USER [AMSA\svtstrefdata] FROM LOGIN [AMSA\svtstrefdata] WITH DEFAULT_SCHEMA = [AMSA\svtstrefdata];
USE [WellnessODS]; CREATE USER [amsa\treagan] FROM LOGIN [amsa\treagan] WITH DEFAULT_SCHEMA = [amsa\treagan];
USE [WellnessODS]; CREATE USER [DBTKUser] FOR LOGIN [DBTKUser] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [ImpervaUser] FOR LOGIN [ImpervaUser] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [teamworks] FOR LOGIN [teamworks] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [TempLinkedServerUser] FOR LOGIN [TempLinkedServerUser] WITH DEFAULT_SCHEMA = [dbo];
--
--
EXEC dbo.sp_addsrvrolemember 'ATSTDBS011\SQLServer2005MSSQLUser$ATSTDBS011$ODS', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'ATSTDBS011\SQLServer2005SQLAgentUser$ATSTDBS011$ODS', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'amsa\ProdDBA', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\ttrent', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\dlake', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'ImpervaUser', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\SvTstSSISExecFisma', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'DBTKUser', 'bulkadmin';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_owner', 'DBTKUser';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_owner', 'ImpervaUser';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_owner', 'teamworks';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\SAS Server Users';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\SQL_DEV_Reader';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\SQL_TST_Reader';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'amsa\treagan';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svtstperson';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svtstrefdata';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'TempLinkedServerUser';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svtstcontactvalidate';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svtstLoan';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datawriter', 'AMSA\svtstperson';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datawriter', 'AMSA\svtstLoan';

USE master; GRANT ADMINISTER BULK OPERATIONS TO [DBTKUser];
--
USE master; GRANT CONNECT SQL TO [AMSA\dlake];
USE master; GRANT CONNECT SQL TO [amsa\ProdDBA];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_DEV_Reader];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_TST_Filestaging_Write];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_TST_Reader];
USE master; GRANT CONNECT SQL TO [AMSA\svtstcontactvalidate];
USE master; GRANT CONNECT SQL TO [AMSA\svtstLoan];
USE master; GRANT CONNECT SQL TO [AMSA\svtstperson];
USE master; GRANT CONNECT SQL TO [AMSA\svtstrefdata];
USE master; GRANT CONNECT SQL TO [AMSA\svtstserviceadapter];
USE master; GRANT CONNECT SQL TO [AMSA\SvTstSSISExecFisma];
USE master; GRANT CONNECT SQL TO [AMSA\treagan];
USE master; GRANT CONNECT SQL TO [AMSA\ttrent];
--
USE master; GRANT CONNECT SQL TO [ATSTDBS011\SQLServer2005MSFTEUser$ATSTDBS011$ODS];
USE master; GRANT CONNECT SQL TO [ATSTDBS011\SQLServer2005MSSQLUser$ATSTDBS011$ODS];
USE master; GRANT CONNECT SQL TO [ATSTDBS011\SQLServer2005SQLAgentUser$ATSTDBS011$ODS];
USE master; GRANT CONNECT SQL TO [DBTKUser];
USE master; GRANT CONNECT SQL TO [ImpervaUser];
USE master; GRANT CONNECT SQL TO [NT AUTHORITY\SYSTEM];
USE master; GRANT CONNECT SQL TO [SvTstMonOSS];
USE master; GRANT CONNECT SQL TO [teamworks];
USE master; GRANT CONNECT SQL TO [TempLinkedServerUser];
USE master; GRANT VIEW ANY DATABASE TO [public];
USE [WellnessODS]; GRANT EXECUTE ON SCHEMA::db_owner TO [teamworks];
USE [WellnessODS]; GRANT ALTER ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\SAS Server Users];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\SQL_DEV_Reader];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\SQL_TST_Reader];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svtstcontactvalidate];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svtstLoan];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svtstperson];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svtstrefdata];
USE [WellnessODS]; GRANT CONNECT TO [amsa\treagan];
--
USE [WellnessODS]; GRANT CONNECT TO [DBTKUser];
USE [WellnessODS]; GRANT CONNECT TO [ImpervaUser];
USE [WellnessODS]; GRANT CONNECT TO [teamworks];
USE [WellnessODS]; GRANT CONNECT TO [TempLinkedServerUser];
USE [WellnessODS]; GRANT CONTROL ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE DEFAULT TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE FUNCTION TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE PROCEDURE TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE ROLE TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE RULE TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE SCHEMA TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE TABLE TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE TYPE TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE VIEW TO [DBTKUser];
USE [WellnessODS]; GRANT DELETE ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT EXECUTE ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT EXECUTE ON SCHEMA::dbo TO [teamworks];
USE [WellnessODS]; GRANT INSERT ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT SELECT ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT SELECT ON sys.all_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.all_objects TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.all_parameters TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.all_sql_modules TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.all_views TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.allocation_units TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.assemblies TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.assembly_files TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.assembly_modules TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.assembly_references TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.assembly_types TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.asymmetric_keys TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.certificates TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.check_constraints TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.column_type_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.column_xml_schema_collection_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.computed_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.conversation_endpoints TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.conversation_groups TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.crypt_properties TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.data_spaces TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.database_files TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.database_permissions TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.database_principal_aliases TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.database_principals TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.database_role_members TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.default_constraints TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.destination_data_spaces TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.event_notifications TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.events TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.extended_procedures TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.extended_properties TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.filegroups TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.foreign_key_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.foreign_keys TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.fulltext_catalogs TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.fulltext_index_catalog_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.fulltext_index_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.fulltext_indexes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.identity_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.index_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.indexes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.internal_tables TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.key_constraints TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.key_encryptions TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.message_type_xml_schema_collection_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.module_assembly_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.numbered_procedure_parameters TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.numbered_procedures TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.objects TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.parameter_type_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.parameter_xml_schema_collection_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.parameters TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.partition_functions TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.partition_parameters TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.partition_range_values TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.partition_schemes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.partitions TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.plan_guides TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.procedures TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.remote_service_bindings TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.routes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.schemas TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.service_contract_message_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.service_contract_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.service_contracts TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.service_message_types TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.service_queue_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.service_queues TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.services TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sql_dependencies TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sql_modules TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.stats TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.stats_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.symmetric_keys TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.synonyms TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.syscolumns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.syscomments TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysconstraints TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysdepends TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysfilegroups TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysfiles TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysforeignkeys TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysfulltextcatalogs TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysindexes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysindexkeys TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysmembers TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysobjects TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.syspermissions TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysprotects TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysreferences TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.syssegments TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.system_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.system_objects TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.system_parameters TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.system_sql_modules TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.system_views TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.systypes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysusers TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.tables TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.transmission_queue TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.trigger_events TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.triggers TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.type_assembly_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.types TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.views TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_indexes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_attributes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_collections TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_component_placements TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_components TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_elements TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_facets TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_model_groups TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_namespaces TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_types TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_wildcard_namespaces TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_wildcards TO [public];
USE [WellnessODS]; GRANT UPDATE ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT VIEW DEFINITION TO [AMSA\SQL_TST_Reader];
USE [WellnessODS]; GRANT VIEW DEFINITION TO [DBTKUser];

--------------------------------------------------------------------------------------------------------------------------------

USE [FileStaging]; CREATE USER [amsa\SQL_TST_Filestaging_Write] FROM LOGIN [amsa\SQL_TST_Filestaging_Write];
USE [FileStaging]; CREATE USER [AMSA\SQL_TST_Reader] FROM LOGIN [AMSA\SQL_TST_Reader];
USE [FileStaging]; CREATE USER [AMSA\svtstserviceadapter] FROM LOGIN [AMSA\svtstserviceadapter] WITH DEFAULT_SCHEMA = [dbo];
USE [FileStaging]; CREATE USER [AMSA\SvTstSSISExecFisma] FROM LOGIN [AMSA\SvTstSSISExecFisma] WITH DEFAULT_SCHEMA = [dbo];
USE [FileStaging]; CREATE USER [DBTKUser] FOR LOGIN [DBTKUser] WITH DEFAULT_SCHEMA = [dbo];
--
--
EXEC dbo.sp_addsrvrolemember 'ATSTDBS011\SQLServer2005MSSQLUser$ATSTDBS011$ODS', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'ATSTDBS011\SQLServer2005SQLAgentUser$ATSTDBS011$ODS', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'amsa\ProdDBA', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\ttrent', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\dlake', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'ImpervaUser', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\SvTstSSISExecFisma', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'DBTKUser', 'bulkadmin';
EXEC [FileStaging].dbo.sp_addrolemember 'db_owner', 'DBTKUser';
EXEC [FileStaging].dbo.sp_addrolemember 'db_accessadmin', 'AMSA\SvTstSSISExecFisma';
EXEC [FileStaging].dbo.sp_addrolemember 'db_datareader', 'AMSA\SQL_TST_Reader';
EXEC [FileStaging].dbo.sp_addrolemember 'db_datareader', 'AMSA\svtstserviceadapter';
EXEC [FileStaging].dbo.sp_addrolemember 'db_datareader', 'AMSA\SvTstSSISExecFisma';
EXEC [FileStaging].dbo.sp_addrolemember 'db_datawriter', 'AMSA\svtstserviceadapter';
EXEC [FileStaging].dbo.sp_addrolemember 'db_datawriter', 'AMSA\SvTstSSISExecFisma';
EXEC [FileStaging].dbo.sp_addrolemember 'db_datawriter', 'amsa\SQL_TST_Filestaging_Write';

USE master; GRANT ADMINISTER BULK OPERATIONS TO [DBTKUser];
--
USE master; GRANT CONNECT SQL TO [AMSA\dlake];
USE master; GRANT CONNECT SQL TO [amsa\ProdDBA];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_DEV_Reader];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_TST_Filestaging_Write];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_TST_Reader];
USE master; GRANT CONNECT SQL TO [AMSA\svtstcontactvalidate];
USE master; GRANT CONNECT SQL TO [AMSA\svtstLoan];
USE master; GRANT CONNECT SQL TO [AMSA\svtstperson];
USE master; GRANT CONNECT SQL TO [AMSA\svtstrefdata];
USE master; GRANT CONNECT SQL TO [AMSA\svtstserviceadapter];
USE master; GRANT CONNECT SQL TO [AMSA\SvTstSSISExecFisma];
USE master; GRANT CONNECT SQL TO [AMSA\treagan];
USE master; GRANT CONNECT SQL TO [AMSA\ttrent];
--
USE master; GRANT CONNECT SQL TO [ATSTDBS011\SQLServer2005MSFTEUser$ATSTDBS011$ODS];
USE master; GRANT CONNECT SQL TO [ATSTDBS011\SQLServer2005MSSQLUser$ATSTDBS011$ODS];
USE master; GRANT CONNECT SQL TO [ATSTDBS011\SQLServer2005SQLAgentUser$ATSTDBS011$ODS];
USE master; GRANT CONNECT SQL TO [DBTKUser];
USE master; GRANT CONNECT SQL TO [ImpervaUser];
USE master; GRANT CONNECT SQL TO [NT AUTHORITY\SYSTEM];
USE master; GRANT CONNECT SQL TO [SvTstMonOSS];
USE master; GRANT CONNECT SQL TO [teamworks];
USE master; GRANT CONNECT SQL TO [TempLinkedServerUser];
USE master; GRANT VIEW ANY DATABASE TO [public];
USE [FileStaging]; GRANT CONNECT TO [amsa\SQL_TST_Filestaging_Write];
USE [FileStaging]; GRANT CONNECT TO [AMSA\SQL_TST_Reader];
USE [FileStaging]; GRANT CONNECT TO [AMSA\svtstserviceadapter];
USE [FileStaging]; GRANT CONNECT TO [AMSA\SvTstSSISExecFisma];
--
USE [FileStaging]; GRANT CONNECT TO [DBTKUser];
USE [FileStaging]; GRANT EXECUTE ON dbo.fssp_LoadXMLRecordToTarget TO [AMSA\svtstserviceadapter];
USE [FileStaging]; GRANT EXECUTE ON dbo.fssp_SetLoadedXMLRecordStatus TO [AMSA\svtstserviceadapter];
USE [FileStaging]; GRANT SELECT ON sys.all_columns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.all_objects TO [public];
USE [FileStaging]; GRANT SELECT ON sys.all_parameters TO [public];
USE [FileStaging]; GRANT SELECT ON sys.all_sql_modules TO [public];
USE [FileStaging]; GRANT SELECT ON sys.all_views TO [public];
USE [FileStaging]; GRANT SELECT ON sys.allocation_units TO [public];
USE [FileStaging]; GRANT SELECT ON sys.assemblies TO [public];
USE [FileStaging]; GRANT SELECT ON sys.assembly_files TO [public];
USE [FileStaging]; GRANT SELECT ON sys.assembly_modules TO [public];
USE [FileStaging]; GRANT SELECT ON sys.assembly_references TO [public];
USE [FileStaging]; GRANT SELECT ON sys.assembly_types TO [public];
USE [FileStaging]; GRANT SELECT ON sys.asymmetric_keys TO [public];
USE [FileStaging]; GRANT SELECT ON sys.certificates TO [public];
USE [FileStaging]; GRANT SELECT ON sys.check_constraints TO [public];
USE [FileStaging]; GRANT SELECT ON sys.column_type_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.column_xml_schema_collection_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.columns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.computed_columns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.conversation_endpoints TO [public];
USE [FileStaging]; GRANT SELECT ON sys.conversation_groups TO [public];
USE [FileStaging]; GRANT SELECT ON sys.crypt_properties TO [public];
USE [FileStaging]; GRANT SELECT ON sys.data_spaces TO [public];
USE [FileStaging]; GRANT SELECT ON sys.database_files TO [public];
USE [FileStaging]; GRANT SELECT ON sys.database_permissions TO [public];
USE [FileStaging]; GRANT SELECT ON sys.database_principal_aliases TO [public];
USE [FileStaging]; GRANT SELECT ON sys.database_principals TO [public];
USE [FileStaging]; GRANT SELECT ON sys.database_role_members TO [public];
USE [FileStaging]; GRANT SELECT ON sys.default_constraints TO [public];
USE [FileStaging]; GRANT SELECT ON sys.destination_data_spaces TO [public];
USE [FileStaging]; GRANT SELECT ON sys.event_notifications TO [public];
USE [FileStaging]; GRANT SELECT ON sys.events TO [public];
USE [FileStaging]; GRANT SELECT ON sys.extended_procedures TO [public];
USE [FileStaging]; GRANT SELECT ON sys.extended_properties TO [public];
USE [FileStaging]; GRANT SELECT ON sys.filegroups TO [public];
USE [FileStaging]; GRANT SELECT ON sys.foreign_key_columns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.foreign_keys TO [public];
USE [FileStaging]; GRANT SELECT ON sys.fulltext_catalogs TO [public];
USE [FileStaging]; GRANT SELECT ON sys.fulltext_index_catalog_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.fulltext_index_columns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.fulltext_indexes TO [public];
USE [FileStaging]; GRANT SELECT ON sys.identity_columns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.index_columns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.indexes TO [public];
USE [FileStaging]; GRANT SELECT ON sys.internal_tables TO [public];
USE [FileStaging]; GRANT SELECT ON sys.key_constraints TO [public];
USE [FileStaging]; GRANT SELECT ON sys.key_encryptions TO [public];
USE [FileStaging]; GRANT SELECT ON sys.message_type_xml_schema_collection_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.module_assembly_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.numbered_procedure_parameters TO [public];
USE [FileStaging]; GRANT SELECT ON sys.numbered_procedures TO [public];
USE [FileStaging]; GRANT SELECT ON sys.objects TO [public];
USE [FileStaging]; GRANT SELECT ON sys.parameter_type_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.parameter_xml_schema_collection_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.parameters TO [public];
USE [FileStaging]; GRANT SELECT ON sys.partition_functions TO [public];
USE [FileStaging]; GRANT SELECT ON sys.partition_parameters TO [public];
USE [FileStaging]; GRANT SELECT ON sys.partition_range_values TO [public];
USE [FileStaging]; GRANT SELECT ON sys.partition_schemes TO [public];
USE [FileStaging]; GRANT SELECT ON sys.partitions TO [public];
USE [FileStaging]; GRANT SELECT ON sys.plan_guides TO [public];
USE [FileStaging]; GRANT SELECT ON sys.procedures TO [public];
USE [FileStaging]; GRANT SELECT ON sys.remote_service_bindings TO [public];
USE [FileStaging]; GRANT SELECT ON sys.routes TO [public];
USE [FileStaging]; GRANT SELECT ON sys.schemas TO [public];
USE [FileStaging]; GRANT SELECT ON sys.service_contract_message_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.service_contract_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.service_contracts TO [public];
USE [FileStaging]; GRANT SELECT ON sys.service_message_types TO [public];
USE [FileStaging]; GRANT SELECT ON sys.service_queue_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.service_queues TO [public];
USE [FileStaging]; GRANT SELECT ON sys.services TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sql_dependencies TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sql_modules TO [public];
USE [FileStaging]; GRANT SELECT ON sys.stats TO [public];
USE [FileStaging]; GRANT SELECT ON sys.stats_columns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.symmetric_keys TO [public];
USE [FileStaging]; GRANT SELECT ON sys.synonyms TO [public];
USE [FileStaging]; GRANT SELECT ON sys.syscolumns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.syscomments TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysconstraints TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysdepends TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysfilegroups TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysfiles TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysforeignkeys TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysfulltextcatalogs TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysindexes TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysindexkeys TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysmembers TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysobjects TO [public];
USE [FileStaging]; GRANT SELECT ON sys.syspermissions TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysprotects TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysreferences TO [public];
USE [FileStaging]; GRANT SELECT ON sys.syssegments TO [public];
USE [FileStaging]; GRANT SELECT ON sys.system_columns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.system_objects TO [public];
USE [FileStaging]; GRANT SELECT ON sys.system_parameters TO [public];
USE [FileStaging]; GRANT SELECT ON sys.system_sql_modules TO [public];
USE [FileStaging]; GRANT SELECT ON sys.system_views TO [public];
USE [FileStaging]; GRANT SELECT ON sys.systypes TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysusers TO [public];
USE [FileStaging]; GRANT SELECT ON sys.tables TO [public];
USE [FileStaging]; GRANT SELECT ON sys.transmission_queue TO [public];
USE [FileStaging]; GRANT SELECT ON sys.trigger_events TO [public];
USE [FileStaging]; GRANT SELECT ON sys.triggers TO [public];
USE [FileStaging]; GRANT SELECT ON sys.type_assembly_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.types TO [public];
USE [FileStaging]; GRANT SELECT ON sys.views TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_indexes TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_attributes TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_collections TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_component_placements TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_components TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_elements TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_facets TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_model_groups TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_namespaces TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_types TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_wildcard_namespaces TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_wildcards TO [public];