USE [WellnessODS]; CREATE USER [amsa\aosborne] FROM LOGIN [amsa\aosborne] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\dgrigorjev] FROM LOGIN [AMSA\dgrigorjev] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\dlake] FROM LOGIN [AMSA\dlake] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\mamante] FROM LOGIN [AMSA\mamante] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\mLiu] FROM LOGIN [AMSA\mLiu] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\pbirch] FROM LOGIN [AMSA\pbirch] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\SQL_DEV_Reader] FROM LOGIN [AMSA\SQL_DEV_Reader];
USE [WellnessODS]; CREATE USER [AMSA\SQL_TST_Reader] FROM LOGIN [AMSA\SQL_TST_Reader];
USE [WellnessODS]; CREATE USER [AMSA\svdevcontactvalidate] FROM LOGIN [AMSA\svdevcontactvalidate] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\svdevLoan] FROM LOGIN [AMSA\svdevLoan] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\svdevperson] FROM LOGIN [AMSA\svdevperson] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\svdevRefData] FROM LOGIN [AMSA\svdevRefData] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [AMSA\treagan] FROM LOGIN [AMSA\treagan] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [DBTKUser] FOR LOGIN [DBTKUser] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [loan] FOR LOGIN [loan] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [person] FOR LOGIN [person] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [svContactValidation] FOR LOGIN [svContactValidation] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [SvDevMonOSS] FOR LOGIN [SvDevMonOSS] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [svDevPerson] FOR LOGIN [svDevPerson] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [teamworks] FOR LOGIN [teamworks] WITH DEFAULT_SCHEMA = [dbo];
USE [WellnessODS]; CREATE USER [TempLinkedServerUser] FOR LOGIN [TempLinkedServerUser] WITH DEFAULT_SCHEMA = [dbo];

--
--
EXEC dbo.sp_addsrvrolemember 'ADEVDBS011\SQLServer2005MSSQLUser$ADEVDBS011$ODS', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'ADEVDBS011\SQLServer2005SQLAgentUser$ADEVDBS011$ODS', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\ProdDBA', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\dlake', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'DBTKUser', 'bulkadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\twhite', 'bulkadmin';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_owner', 'AMSA\mLiu';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_owner', 'DBTKUser';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_owner', 'teamworks';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_owner', 'amsa\aosborne';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_owner', 'svDevPerson';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\pbirch';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\SQL_DEV_Reader';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\SQL_TST_Reader';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svdevperson';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\dlake';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\treagan';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'svContactValidation';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'SvDevMonOSS';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'TempLinkedServerUser';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'person';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'loan';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svdevcontactvalidate';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svdevRefData';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datareader', 'AMSA\svdevLoan';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datawriter', 'AMSA\svdevperson';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datawriter', 'AMSA\dlake';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datawriter', 'svContactValidation';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datawriter', 'person';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datawriter', 'loan';
EXEC [WellnessODS].dbo.sp_addrolemember 'db_datawriter', 'AMSA\svdevLoan';

USE master; GRANT ADMINISTER BULK OPERATIONS TO [AMSA\SQL_DEV_Reader];
USE master; GRANT ADMINISTER BULK OPERATIONS TO [AMSA\SvDevSSISExecFisma];
USE master; GRANT ADMINISTER BULK OPERATIONS TO [DBTKUser];
USE master; GRANT ALTER ANY CONNECTION TO [AMSA\SQL_DEV_Reader];
USE master; GRANT ALTER ANY DATABASE TO [AMSA\SQL_DEV_Reader];
USE master; GRANT ALTER TRACE TO [AMSA\aosborne];
USE master; GRANT ALTER TRACE TO [AMSA\SQL_DEV_Reader];
--
USE master; GRANT CONNECT SQL TO [ADEVDBS011\SQLServer2005MSFTEUser$ADEVDBS011$ODS];
USE master; GRANT CONNECT SQL TO [ADEVDBS011\SQLServer2005MSSQLUser$ADEVDBS011$ODS];
USE master; GRANT CONNECT SQL TO [ADEVDBS011\SQLServer2005SQLAgentUser$ADEVDBS011$ODS];
USE master; GRANT CONNECT SQL TO [AMSA\aosborne];
USE master; GRANT CONNECT SQL TO [AMSA\dlake];
USE master; GRANT CONNECT SQL TO [AMSA\mamante];
USE master; GRANT CONNECT SQL TO [AMSA\mLiu];
USE master; GRANT CONNECT SQL TO [AMSA\pbirch];
USE master; GRANT CONNECT SQL TO [AMSA\ProdDBA];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_DEV_Reader];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_TST_Reader];
USE master; GRANT CONNECT SQL TO [AMSA\svdevcontactvalidate];
USE master; GRANT CONNECT SQL TO [AMSA\svdevLoan];
USE master; GRANT CONNECT SQL TO [AMSA\svdevperson];
USE master; GRANT CONNECT SQL TO [AMSA\svdevRefData];
USE master; GRANT CONNECT SQL TO [AMSA\svdevserviceadapter];
USE master; GRANT CONNECT SQL TO [AMSA\SvDevSSISExecFisma];
USE master; GRANT CONNECT SQL TO [AMSA\treagan];
USE master; GRANT CONNECT SQL TO [AMSA\twhite];
--
USE master; GRANT CONNECT SQL TO [DBTKUser];
USE master; GRANT CONNECT SQL TO [loan];
USE master; GRANT CONNECT SQL TO [NT AUTHORITY\SYSTEM];
USE master; GRANT CONNECT SQL TO [person];
USE master; GRANT CONNECT SQL TO [svContactValidation];
USE master; GRANT CONNECT SQL TO [SvDevMonOSS];
USE master; GRANT CONNECT SQL TO [svDevPerson];
USE master; GRANT CONNECT SQL TO [teamworks];
USE master; GRANT CONNECT SQL TO [TempLinkedServerUser];
USE master; GRANT CREATE ANY DATABASE TO [AMSA\SQL_DEV_Reader];
USE master; GRANT VIEW ANY DATABASE TO [public];
USE master; GRANT VIEW ANY DEFINITION TO [AMSA\SQL_DEV_Reader];
USE master; GRANT VIEW SERVER STATE TO [AMSA\SQL_DEV_Reader];
USE [WellnessODS]; GRANT EXECUTE ON SCHEMA::db_owner TO [teamworks];
USE [WellnessODS]; GRANT ALTER ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT CONNECT TO [amsa\aosborne];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\dgrigorjev];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\dlake];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\mamante];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\mLiu];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\pbirch];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\SQL_DEV_Reader];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\SQL_TST_Reader];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svdevcontactvalidate];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svdevLoan];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svdevperson];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\svdevRefData];
USE [WellnessODS]; GRANT CONNECT TO [AMSA\treagan];
--
USE [WellnessODS]; GRANT CONNECT TO [DBTKUser];
USE [WellnessODS]; GRANT CONNECT TO [loan];
USE [WellnessODS]; GRANT CONNECT TO [person];
USE [WellnessODS]; GRANT CONNECT TO [svContactValidation];
USE [WellnessODS]; GRANT CONNECT TO [SvDevMonOSS];
USE [WellnessODS]; GRANT CONNECT TO [svDevPerson];
USE [WellnessODS]; GRANT CONNECT TO [teamworks];
USE [WellnessODS]; GRANT CONNECT TO [TempLinkedServerUser];
USE [WellnessODS]; GRANT CREATE DEFAULT TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE FUNCTION TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE PROCEDURE TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE ROLE TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE RULE TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE SCHEMA TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE TABLE TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE TYPE TO [DBTKUser];
USE [WellnessODS]; GRANT CREATE VIEW TO [DBTKUser];
USE [WellnessODS]; GRANT DELETE ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT EXECUTE ON SCHEMA::dbo TO [AMSA\mamante];
USE [WellnessODS]; GRANT EXECUTE ON SCHEMA::dbo TO [AMSA\treagan];
USE [WellnessODS]; GRANT EXECUTE ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT INSERT ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT SELECT ON SCHEMA::dbo TO [AMSA\treagan];
USE [WellnessODS]; GRANT SELECT ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT SELECT ON sys.all_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.all_objects TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.all_parameters TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.all_sql_modules TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.all_views TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.allocation_units TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.assemblies TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.assembly_files TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.assembly_modules TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.assembly_references TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.assembly_types TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.asymmetric_keys TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.certificates TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.check_constraints TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.column_type_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.column_xml_schema_collection_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.computed_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.conversation_endpoints TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.conversation_groups TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.crypt_properties TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.data_spaces TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.database_files TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.database_permissions TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.database_principal_aliases TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.database_principals TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.database_role_members TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.default_constraints TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.destination_data_spaces TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.event_notifications TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.events TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.extended_procedures TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.extended_properties TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.filegroups TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.foreign_key_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.foreign_keys TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.fulltext_catalogs TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.fulltext_index_catalog_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.fulltext_index_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.fulltext_indexes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.identity_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.index_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.indexes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.internal_tables TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.key_constraints TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.key_encryptions TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.message_type_xml_schema_collection_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.module_assembly_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.numbered_procedure_parameters TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.numbered_procedures TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.objects TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.parameter_type_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.parameter_xml_schema_collection_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.parameters TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.partition_functions TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.partition_parameters TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.partition_range_values TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.partition_schemes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.partitions TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.plan_guides TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.procedures TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.remote_service_bindings TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.routes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.schemas TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.service_contract_message_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.service_contract_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.service_contracts TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.service_message_types TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.service_queue_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.service_queues TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.services TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sql_dependencies TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sql_modules TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.stats TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.stats_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.symmetric_keys TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.synonyms TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.syscolumns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.syscomments TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysconstraints TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysdepends TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysfilegroups TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysfiles TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysforeignkeys TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysfulltextcatalogs TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysindexes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysindexkeys TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysmembers TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysobjects TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.syspermissions TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysprotects TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysreferences TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.syssegments TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.system_columns TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.system_objects TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.system_parameters TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.system_sql_modules TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.system_views TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.systypes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.sysusers TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.tables TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.transmission_queue TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.trigger_events TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.triggers TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.type_assembly_usages TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.types TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.views TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_indexes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_attributes TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_collections TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_component_placements TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_components TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_elements TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_facets TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_model_groups TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_namespaces TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_types TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_wildcard_namespaces TO [public];
USE [WellnessODS]; GRANT SELECT ON sys.xml_schema_wildcards TO [public];
USE [WellnessODS]; GRANT UPDATE ON SCHEMA::dbo TO [DBTKUser];
USE [WellnessODS]; GRANT VIEW DEFINITION TO [DBTKUser];
USE [WellnessODS]; GRANT VIEW DEFINITION ON SCHEMA::dbo TO [AMSA\mamante];
USE [WellnessODS]; GRANT VIEW DEFINITION ON SCHEMA::dbo TO [AMSA\SQL_DEV_Reader];
USE [WellnessODS]; GRANT VIEW DEFINITION ON SCHEMA::dbo TO [AMSA\treagan];

---------------------------------------------------------------------------------------------------------

USE [FileStaging]; CREATE USER [AMSA\dgrigorjev] FROM LOGIN [AMSA\dgrigorjev] WITH DEFAULT_SCHEMA = [dbo];
USE [FileStaging]; CREATE USER [AMSA\dlake] FROM LOGIN [AMSA\dlake] WITH DEFAULT_SCHEMA = [dbo];
USE [FileStaging]; CREATE USER [AMSA\SQL_DEV_Reader] FROM LOGIN [AMSA\SQL_DEV_Reader];
USE [FileStaging]; CREATE USER [AMSA\SQL_TST_Reader] FROM LOGIN [AMSA\SQL_TST_Reader];
USE [FileStaging]; CREATE USER [AMSA\svdevserviceadapter] FROM LOGIN [AMSA\svdevserviceadapter] WITH DEFAULT_SCHEMA = [dbo];
USE [FileStaging]; CREATE USER [AMSA\SvDevSSISExecFisma] FROM LOGIN [AMSA\SvDevSSISExecFisma] WITH DEFAULT_SCHEMA = [dbo];
USE [FileStaging]; CREATE USER [amsa\twhite] FROM LOGIN [amsa\twhite] WITH DEFAULT_SCHEMA = [dbo];
USE [FileStaging]; CREATE USER [DBTKUser] FOR LOGIN [DBTKUser] WITH DEFAULT_SCHEMA = [dbo];

--
--
EXEC dbo.sp_addsrvrolemember 'ADEVDBS011\SQLServer2005MSSQLUser$ADEVDBS011$ODS', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'ADEVDBS011\SQLServer2005SQLAgentUser$ADEVDBS011$ODS', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\ProdDBA', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\dlake', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'DBTKUser', 'bulkadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\twhite', 'bulkadmin';
EXEC [FileStaging].dbo.sp_addrolemember 'db_owner', 'DBTKUser';
EXEC [FileStaging].dbo.sp_addrolemember 'db_owner', 'amsa\twhite';
EXEC [FileStaging].dbo.sp_addrolemember 'db_datareader', 'amsa\twhite';
EXEC [FileStaging].dbo.sp_addrolemember 'db_datareader', 'AMSA\SQL_DEV_Reader';
EXEC [FileStaging].dbo.sp_addrolemember 'db_datareader', 'AMSA\dlake';
EXEC [FileStaging].dbo.sp_addrolemember 'db_datareader', 'AMSA\SQL_TST_Reader';
EXEC [FileStaging].dbo.sp_addrolemember 'db_datareader', 'AMSA\svdevserviceadapter';
EXEC [FileStaging].dbo.sp_addrolemember 'db_datawriter', 'amsa\twhite';
EXEC [FileStaging].dbo.sp_addrolemember 'db_datawriter', 'AMSA\dlake';
EXEC [FileStaging].dbo.sp_addrolemember 'db_datawriter', 'AMSA\svdevserviceadapter';

USE master; GRANT ADMINISTER BULK OPERATIONS TO [AMSA\SQL_DEV_Reader];
USE master; GRANT ADMINISTER BULK OPERATIONS TO [AMSA\SvDevSSISExecFisma];
USE master; GRANT ADMINISTER BULK OPERATIONS TO [DBTKUser];
USE master; GRANT ALTER ANY CONNECTION TO [AMSA\SQL_DEV_Reader];
USE master; GRANT ALTER ANY DATABASE TO [AMSA\SQL_DEV_Reader];
USE master; GRANT ALTER TRACE TO [AMSA\aosborne];
USE master; GRANT ALTER TRACE TO [AMSA\SQL_DEV_Reader];
--
USE master; GRANT CONNECT SQL TO [ADEVDBS011\SQLServer2005MSFTEUser$ADEVDBS011$ODS];
USE master; GRANT CONNECT SQL TO [ADEVDBS011\SQLServer2005MSSQLUser$ADEVDBS011$ODS];
USE master; GRANT CONNECT SQL TO [ADEVDBS011\SQLServer2005SQLAgentUser$ADEVDBS011$ODS];
USE master; GRANT CONNECT SQL TO [AMSA\aosborne];
USE master; GRANT CONNECT SQL TO [AMSA\dlake];
USE master; GRANT CONNECT SQL TO [AMSA\mamante];
USE master; GRANT CONNECT SQL TO [AMSA\mLiu];
USE master; GRANT CONNECT SQL TO [AMSA\pbirch];
USE master; GRANT CONNECT SQL TO [AMSA\ProdDBA];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_DEV_Reader];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_TST_Reader];
USE master; GRANT CONNECT SQL TO [AMSA\svdevcontactvalidate];
USE master; GRANT CONNECT SQL TO [AMSA\svdevLoan];
USE master; GRANT CONNECT SQL TO [AMSA\svdevperson];
USE master; GRANT CONNECT SQL TO [AMSA\svdevRefData];
USE master; GRANT CONNECT SQL TO [AMSA\svdevserviceadapter];
USE master; GRANT CONNECT SQL TO [AMSA\SvDevSSISExecFisma];
USE master; GRANT CONNECT SQL TO [AMSA\treagan];
USE master; GRANT CONNECT SQL TO [AMSA\twhite];
--
USE master; GRANT CONNECT SQL TO [DBTKUser];
USE master; GRANT CONNECT SQL TO [loan];
USE master; GRANT CONNECT SQL TO [NT AUTHORITY\SYSTEM];
USE master; GRANT CONNECT SQL TO [person];
USE master; GRANT CONNECT SQL TO [svContactValidation];
USE master; GRANT CONNECT SQL TO [SvDevMonOSS];
USE master; GRANT CONNECT SQL TO [svDevPerson];
USE master; GRANT CONNECT SQL TO [teamworks];
USE master; GRANT CONNECT SQL TO [TempLinkedServerUser];
USE master; GRANT CREATE ANY DATABASE TO [AMSA\SQL_DEV_Reader];
USE master; GRANT VIEW ANY DATABASE TO [public];
USE master; GRANT VIEW ANY DEFINITION TO [AMSA\SQL_DEV_Reader];
USE master; GRANT VIEW SERVER STATE TO [AMSA\SQL_DEV_Reader];
USE [FileStaging]; GRANT ALTER ON SCHEMA::dbo TO [AMSA\SvDevSSISExecFisma];
USE [FileStaging]; GRANT CONNECT TO [AMSA\dgrigorjev];
USE [FileStaging]; GRANT CONNECT TO [AMSA\dlake];
USE [FileStaging]; GRANT CONNECT TO [AMSA\SQL_DEV_Reader];
USE [FileStaging]; GRANT CONNECT TO [AMSA\SQL_TST_Reader];
USE [FileStaging]; GRANT CONNECT TO [AMSA\svdevserviceadapter];
USE [FileStaging]; GRANT CONNECT TO [AMSA\SvDevSSISExecFisma];
USE [FileStaging]; GRANT CONNECT TO [amsa\twhite];
--
USE [FileStaging]; GRANT CONNECT TO [DBTKUser];
USE [FileStaging]; GRANT DELETE ON SCHEMA::dbo TO [AMSA\SvDevSSISExecFisma];
USE [FileStaging]; GRANT EXECUTE ON SCHEMA::dbo TO [AMSA\SvDevSSISExecFisma];
USE [FileStaging]; GRANT EXECUTE ON dbo.fssp_LoadXMLRecordToTarget TO [AMSA\svdevserviceadapter];
USE [FileStaging]; GRANT EXECUTE ON dbo.fssp_SetLoadedXMLRecordStatus TO [AMSA\svdevserviceadapter];
USE [FileStaging]; GRANT INSERT ON SCHEMA::dbo TO [AMSA\SvDevSSISExecFisma];
USE [FileStaging]; GRANT SELECT ON SCHEMA::dbo TO [AMSA\SvDevSSISExecFisma];
USE [FileStaging]; GRANT SELECT ON sys.all_columns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.all_objects TO [public];
USE [FileStaging]; GRANT SELECT ON sys.all_parameters TO [public];
USE [FileStaging]; GRANT SELECT ON sys.all_sql_modules TO [public];
USE [FileStaging]; GRANT SELECT ON sys.all_views TO [public];
USE [FileStaging]; GRANT SELECT ON sys.allocation_units TO [public];
USE [FileStaging]; GRANT SELECT ON sys.assemblies TO [public];
USE [FileStaging]; GRANT SELECT ON sys.assembly_files TO [public];
USE [FileStaging]; GRANT SELECT ON sys.assembly_modules TO [public];
USE [FileStaging]; GRANT SELECT ON sys.assembly_references TO [public];
USE [FileStaging]; GRANT SELECT ON sys.assembly_types TO [public];
USE [FileStaging]; GRANT SELECT ON sys.asymmetric_keys TO [public];
USE [FileStaging]; GRANT SELECT ON sys.certificates TO [public];
USE [FileStaging]; GRANT SELECT ON sys.check_constraints TO [public];
USE [FileStaging]; GRANT SELECT ON sys.column_type_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.column_xml_schema_collection_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.columns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.computed_columns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.conversation_endpoints TO [public];
USE [FileStaging]; GRANT SELECT ON sys.conversation_groups TO [public];
USE [FileStaging]; GRANT SELECT ON sys.crypt_properties TO [public];
USE [FileStaging]; GRANT SELECT ON sys.data_spaces TO [public];
USE [FileStaging]; GRANT SELECT ON sys.database_files TO [public];
USE [FileStaging]; GRANT SELECT ON sys.database_permissions TO [public];
USE [FileStaging]; GRANT SELECT ON sys.database_principal_aliases TO [public];
USE [FileStaging]; GRANT SELECT ON sys.database_principals TO [public];
USE [FileStaging]; GRANT SELECT ON sys.database_role_members TO [public];
USE [FileStaging]; GRANT SELECT ON sys.default_constraints TO [public];
USE [FileStaging]; GRANT SELECT ON sys.destination_data_spaces TO [public];
USE [FileStaging]; GRANT SELECT ON sys.event_notifications TO [public];
USE [FileStaging]; GRANT SELECT ON sys.events TO [public];
USE [FileStaging]; GRANT SELECT ON sys.extended_procedures TO [public];
USE [FileStaging]; GRANT SELECT ON sys.extended_properties TO [public];
USE [FileStaging]; GRANT SELECT ON sys.filegroups TO [public];
USE [FileStaging]; GRANT SELECT ON sys.foreign_key_columns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.foreign_keys TO [public];
USE [FileStaging]; GRANT SELECT ON sys.fulltext_catalogs TO [public];
USE [FileStaging]; GRANT SELECT ON sys.fulltext_index_catalog_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.fulltext_index_columns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.fulltext_indexes TO [public];
USE [FileStaging]; GRANT SELECT ON sys.identity_columns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.index_columns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.indexes TO [public];
USE [FileStaging]; GRANT SELECT ON sys.internal_tables TO [public];
USE [FileStaging]; GRANT SELECT ON sys.key_constraints TO [public];
USE [FileStaging]; GRANT SELECT ON sys.key_encryptions TO [public];
USE [FileStaging]; GRANT SELECT ON sys.message_type_xml_schema_collection_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.module_assembly_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.numbered_procedure_parameters TO [public];
USE [FileStaging]; GRANT SELECT ON sys.numbered_procedures TO [public];
USE [FileStaging]; GRANT SELECT ON sys.objects TO [public];
USE [FileStaging]; GRANT SELECT ON sys.parameter_type_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.parameter_xml_schema_collection_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.parameters TO [public];
USE [FileStaging]; GRANT SELECT ON sys.partition_functions TO [public];
USE [FileStaging]; GRANT SELECT ON sys.partition_parameters TO [public];
USE [FileStaging]; GRANT SELECT ON sys.partition_range_values TO [public];
USE [FileStaging]; GRANT SELECT ON sys.partition_schemes TO [public];
USE [FileStaging]; GRANT SELECT ON sys.partitions TO [public];
USE [FileStaging]; GRANT SELECT ON sys.plan_guides TO [public];
USE [FileStaging]; GRANT SELECT ON sys.procedures TO [public];
USE [FileStaging]; GRANT SELECT ON sys.remote_service_bindings TO [public];
USE [FileStaging]; GRANT SELECT ON sys.routes TO [public];
USE [FileStaging]; GRANT SELECT ON sys.schemas TO [public];
USE [FileStaging]; GRANT SELECT ON sys.service_contract_message_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.service_contract_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.service_contracts TO [public];
USE [FileStaging]; GRANT SELECT ON sys.service_message_types TO [public];
USE [FileStaging]; GRANT SELECT ON sys.service_queue_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.service_queues TO [public];
USE [FileStaging]; GRANT SELECT ON sys.services TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sql_dependencies TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sql_modules TO [public];
USE [FileStaging]; GRANT SELECT ON sys.stats TO [public];
USE [FileStaging]; GRANT SELECT ON sys.stats_columns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.symmetric_keys TO [public];
USE [FileStaging]; GRANT SELECT ON sys.synonyms TO [public];
USE [FileStaging]; GRANT SELECT ON sys.syscolumns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.syscomments TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysconstraints TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysdepends TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysfilegroups TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysfiles TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysforeignkeys TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysfulltextcatalogs TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysindexes TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysindexkeys TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysmembers TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysobjects TO [public];
USE [FileStaging]; GRANT SELECT ON sys.syspermissions TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysprotects TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysreferences TO [public];
USE [FileStaging]; GRANT SELECT ON sys.syssegments TO [public];
USE [FileStaging]; GRANT SELECT ON sys.system_columns TO [public];
USE [FileStaging]; GRANT SELECT ON sys.system_objects TO [public];
USE [FileStaging]; GRANT SELECT ON sys.system_parameters TO [public];
USE [FileStaging]; GRANT SELECT ON sys.system_sql_modules TO [public];
USE [FileStaging]; GRANT SELECT ON sys.system_views TO [public];
USE [FileStaging]; GRANT SELECT ON sys.systypes TO [public];
USE [FileStaging]; GRANT SELECT ON sys.sysusers TO [public];
USE [FileStaging]; GRANT SELECT ON sys.tables TO [public];
USE [FileStaging]; GRANT SELECT ON sys.transmission_queue TO [public];
USE [FileStaging]; GRANT SELECT ON sys.trigger_events TO [public];
USE [FileStaging]; GRANT SELECT ON sys.triggers TO [public];
USE [FileStaging]; GRANT SELECT ON sys.type_assembly_usages TO [public];
USE [FileStaging]; GRANT SELECT ON sys.types TO [public];
USE [FileStaging]; GRANT SELECT ON sys.views TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_indexes TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_attributes TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_collections TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_component_placements TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_components TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_elements TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_facets TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_model_groups TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_namespaces TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_types TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_wildcard_namespaces TO [public];
USE [FileStaging]; GRANT SELECT ON sys.xml_schema_wildcards TO [public];
USE [FileStaging]; GRANT UPDATE ON SCHEMA::dbo TO [AMSA\SvDevSSISExecFisma];