USE [SEL]; CREATE USER [AMSA\SQL_STA_SEL_READ] FROM LOGIN [AMSA\SQL_STA_SEL_READ];
USE [SEL]; CREATE USER [AMSA\SQL_STA_SEL_WRITE] FROM LOGIN [AMSA\SQL_STA_SEL_WRITE];
USE [SEL]; CREATE USER [AMSA\svstacontactvalidate] FROM LOGIN [AMSA\svstacontactvalidate] WITH DEFAULT_SCHEMA = [dbo];
USE [SEL]; CREATE USER [AMSA\svstaLoan] FROM LOGIN [AMSA\svstaLoan] WITH DEFAULT_SCHEMA = [dbo];
USE [SEL]; CREATE USER [AMSA\svstaLoanMgt] FROM LOGIN [AMSA\svstaLoanMgt] WITH DEFAULT_SCHEMA = [dbo];
USE [SEL]; CREATE USER [AMSA\svstaperson] FROM LOGIN [AMSA\svstaperson] WITH DEFAULT_SCHEMA = [dbo];
USE [SEL]; CREATE USER [AMSA\svstapersonmgt] FROM LOGIN [AMSA\svstapersonmgt] WITH DEFAULT_SCHEMA = [dbo];
USE [SEL]; CREATE USER [AMSA\svstaRefData] FROM LOGIN [AMSA\svstaRefData] WITH DEFAULT_SCHEMA = [dbo];
USE [SEL]; CREATE USER [AMSA\svstaserviceadapter] FROM LOGIN [AMSA\svstaserviceadapter] WITH DEFAULT_SCHEMA = [dbo];
USE [SEL]; CREATE USER [DBTKUSER] FOR LOGIN [DBTKUSER] WITH DEFAULT_SCHEMA = [dbo];

--
--
EXEC dbo.sp_addsrvrolemember 'AMSA\SQL Cluster STA Server Service Group', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\SQL Cluster STA Agent Service Group', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\prodDBA', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\SvSTAWincluster', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\dlake', 'serveradmin';
EXEC dbo.sp_addsrvrolemember 'DBTKUSER', 'bulkadmin';
EXEC [SEL].dbo.sp_addrolemember 'db_owner', 'DBTKUSER';
EXEC [SEL].dbo.sp_addrolemember 'db_datareader', 'AMSA\SQL_STA_SEL_READ';
EXEC [SEL].dbo.sp_addrolemember 'db_datareader', 'AMSA\svstacontactvalidate';
EXEC [SEL].dbo.sp_addrolemember 'db_datareader', 'AMSA\svstaLoan';
EXEC [SEL].dbo.sp_addrolemember 'db_datareader', 'AMSA\svstaperson';
EXEC [SEL].dbo.sp_addrolemember 'db_datareader', 'AMSA\svstaRefData';
EXEC [SEL].dbo.sp_addrolemember 'db_datareader', 'AMSA\svstaserviceadapter';
EXEC [SEL].dbo.sp_addrolemember 'db_datareader', 'AMSA\svstapersonmgt';
EXEC [SEL].dbo.sp_addrolemember 'db_datareader', 'AMSA\svstaLoanMgt';
EXEC [SEL].dbo.sp_addrolemember 'db_datawriter', 'AMSA\SQL_STA_SEL_WRITE';

--
USE master; GRANT CONNECT SQL TO [AMSA\dlake];
USE master; GRANT CONNECT SQL TO [AMSA\prodDBA];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Agent Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Server Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_STA_SEL_READ];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_STA_SEL_WRITE];
USE master; GRANT CONNECT SQL TO [AMSA\svstacontactvalidate];
USE master; GRANT CONNECT SQL TO [AMSA\svstaLoan];
USE master; GRANT CONNECT SQL TO [AMSA\svstaLoanMgt];
USE master; GRANT CONNECT SQL TO [AMSA\svstaperson];
USE master; GRANT CONNECT SQL TO [AMSA\svstapersonmgt];
USE master; GRANT CONNECT SQL TO [AMSA\svstaRefData];
USE master; GRANT CONNECT SQL TO [AMSA\svstaserviceadapter];
USE master; GRANT CONNECT SQL TO [AMSA\SvSTAWincluster];
--
USE master; GRANT CONNECT SQL TO [DBTKUSER];
USE master; GRANT CONNECT SQL TO [NT AUTHORITY\SYSTEM];
USE master; GRANT VIEW ANY DATABASE TO [public];
USE [SEL]; GRANT CONNECT TO [AMSA\SQL_STA_SEL_READ];
USE [SEL]; GRANT CONNECT TO [AMSA\SQL_STA_SEL_WRITE];
USE [SEL]; GRANT CONNECT TO [AMSA\svstacontactvalidate];
USE [SEL]; GRANT CONNECT TO [AMSA\svstaLoan];
USE [SEL]; GRANT CONNECT TO [AMSA\svstaLoanMgt];
USE [SEL]; GRANT CONNECT TO [AMSA\svstaperson];
USE [SEL]; GRANT CONNECT TO [AMSA\svstapersonmgt];
USE [SEL]; GRANT CONNECT TO [AMSA\svstaRefData];
USE [SEL]; GRANT CONNECT TO [AMSA\svstaserviceadapter];
--
USE [SEL]; GRANT CONNECT TO [DBTKUSER];
USE [SEL]; GRANT SELECT ON sys.all_columns TO [public];
USE [SEL]; GRANT SELECT ON sys.all_objects TO [public];
USE [SEL]; GRANT SELECT ON sys.all_parameters TO [public];
USE [SEL]; GRANT SELECT ON sys.all_sql_modules TO [public];
USE [SEL]; GRANT SELECT ON sys.all_views TO [public];
USE [SEL]; GRANT SELECT ON sys.allocation_units TO [public];
USE [SEL]; GRANT SELECT ON sys.assemblies TO [public];
USE [SEL]; GRANT SELECT ON sys.assembly_files TO [public];
USE [SEL]; GRANT SELECT ON sys.assembly_modules TO [public];
USE [SEL]; GRANT SELECT ON sys.assembly_references TO [public];
USE [SEL]; GRANT SELECT ON sys.assembly_types TO [public];
USE [SEL]; GRANT SELECT ON sys.asymmetric_keys TO [public];
USE [SEL]; GRANT SELECT ON sys.certificates TO [public];
USE [SEL]; GRANT SELECT ON sys.check_constraints TO [public];
USE [SEL]; GRANT SELECT ON sys.column_type_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.column_xml_schema_collection_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.columns TO [public];
USE [SEL]; GRANT SELECT ON sys.computed_columns TO [public];
USE [SEL]; GRANT SELECT ON sys.conversation_endpoints TO [public];
USE [SEL]; GRANT SELECT ON sys.conversation_groups TO [public];
USE [SEL]; GRANT SELECT ON sys.crypt_properties TO [public];
USE [SEL]; GRANT SELECT ON sys.data_spaces TO [public];
USE [SEL]; GRANT SELECT ON sys.database_files TO [public];
USE [SEL]; GRANT SELECT ON sys.database_permissions TO [public];
USE [SEL]; GRANT SELECT ON sys.database_principal_aliases TO [public];
USE [SEL]; GRANT SELECT ON sys.database_principals TO [public];
USE [SEL]; GRANT SELECT ON sys.database_role_members TO [public];
USE [SEL]; GRANT SELECT ON sys.default_constraints TO [public];
USE [SEL]; GRANT SELECT ON sys.destination_data_spaces TO [public];
USE [SEL]; GRANT SELECT ON sys.event_notifications TO [public];
USE [SEL]; GRANT SELECT ON sys.events TO [public];
USE [SEL]; GRANT SELECT ON sys.extended_procedures TO [public];
USE [SEL]; GRANT SELECT ON sys.extended_properties TO [public];
USE [SEL]; GRANT SELECT ON sys.filegroups TO [public];
USE [SEL]; GRANT SELECT ON sys.foreign_key_columns TO [public];
USE [SEL]; GRANT SELECT ON sys.foreign_keys TO [public];
USE [SEL]; GRANT SELECT ON sys.fulltext_catalogs TO [public];
USE [SEL]; GRANT SELECT ON sys.fulltext_index_catalog_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.fulltext_index_columns TO [public];
USE [SEL]; GRANT SELECT ON sys.fulltext_indexes TO [public];
USE [SEL]; GRANT SELECT ON sys.identity_columns TO [public];
USE [SEL]; GRANT SELECT ON sys.index_columns TO [public];
USE [SEL]; GRANT SELECT ON sys.indexes TO [public];
USE [SEL]; GRANT SELECT ON sys.internal_tables TO [public];
USE [SEL]; GRANT SELECT ON sys.key_constraints TO [public];
USE [SEL]; GRANT SELECT ON sys.key_encryptions TO [public];
USE [SEL]; GRANT SELECT ON sys.message_type_xml_schema_collection_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.module_assembly_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.numbered_procedure_parameters TO [public];
USE [SEL]; GRANT SELECT ON sys.numbered_procedures TO [public];
USE [SEL]; GRANT SELECT ON sys.objects TO [public];
USE [SEL]; GRANT SELECT ON sys.parameter_type_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.parameter_xml_schema_collection_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.parameters TO [public];
USE [SEL]; GRANT SELECT ON sys.partition_functions TO [public];
USE [SEL]; GRANT SELECT ON sys.partition_parameters TO [public];
USE [SEL]; GRANT SELECT ON sys.partition_range_values TO [public];
USE [SEL]; GRANT SELECT ON sys.partition_schemes TO [public];
USE [SEL]; GRANT SELECT ON sys.partitions TO [public];
USE [SEL]; GRANT SELECT ON sys.plan_guides TO [public];
USE [SEL]; GRANT SELECT ON sys.procedures TO [public];
USE [SEL]; GRANT SELECT ON sys.remote_service_bindings TO [public];
USE [SEL]; GRANT SELECT ON sys.routes TO [public];
USE [SEL]; GRANT SELECT ON sys.schemas TO [public];
USE [SEL]; GRANT SELECT ON sys.service_contract_message_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.service_contract_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.service_contracts TO [public];
USE [SEL]; GRANT SELECT ON sys.service_message_types TO [public];
USE [SEL]; GRANT SELECT ON sys.service_queue_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.service_queues TO [public];
USE [SEL]; GRANT SELECT ON sys.services TO [public];
USE [SEL]; GRANT SELECT ON sys.sql_dependencies TO [public];
USE [SEL]; GRANT SELECT ON sys.sql_modules TO [public];
USE [SEL]; GRANT SELECT ON sys.stats TO [public];
USE [SEL]; GRANT SELECT ON sys.stats_columns TO [public];
USE [SEL]; GRANT SELECT ON sys.symmetric_keys TO [public];
USE [SEL]; GRANT SELECT ON sys.synonyms TO [public];
USE [SEL]; GRANT SELECT ON sys.syscolumns TO [public];
USE [SEL]; GRANT SELECT ON sys.syscomments TO [public];
USE [SEL]; GRANT SELECT ON sys.sysconstraints TO [public];
USE [SEL]; GRANT SELECT ON sys.sysdepends TO [public];
USE [SEL]; GRANT SELECT ON sys.sysfilegroups TO [public];
USE [SEL]; GRANT SELECT ON sys.sysfiles TO [public];
USE [SEL]; GRANT SELECT ON sys.sysforeignkeys TO [public];
USE [SEL]; GRANT SELECT ON sys.sysfulltextcatalogs TO [public];
USE [SEL]; GRANT SELECT ON sys.sysindexes TO [public];
USE [SEL]; GRANT SELECT ON sys.sysindexkeys TO [public];
USE [SEL]; GRANT SELECT ON sys.sysmembers TO [public];
USE [SEL]; GRANT SELECT ON sys.sysobjects TO [public];
USE [SEL]; GRANT SELECT ON sys.syspermissions TO [public];
USE [SEL]; GRANT SELECT ON sys.sysprotects TO [public];
USE [SEL]; GRANT SELECT ON sys.sysreferences TO [public];
USE [SEL]; GRANT SELECT ON sys.syssegments TO [public];
USE [SEL]; GRANT SELECT ON sys.system_columns TO [public];
USE [SEL]; GRANT SELECT ON sys.system_objects TO [public];
USE [SEL]; GRANT SELECT ON sys.system_parameters TO [public];
USE [SEL]; GRANT SELECT ON sys.system_sql_modules TO [public];
USE [SEL]; GRANT SELECT ON sys.system_views TO [public];
USE [SEL]; GRANT SELECT ON sys.systypes TO [public];
USE [SEL]; GRANT SELECT ON sys.sysusers TO [public];
USE [SEL]; GRANT SELECT ON sys.tables TO [public];
USE [SEL]; GRANT SELECT ON sys.transmission_queue TO [public];
USE [SEL]; GRANT SELECT ON sys.trigger_events TO [public];
USE [SEL]; GRANT SELECT ON sys.triggers TO [public];
USE [SEL]; GRANT SELECT ON sys.type_assembly_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.types TO [public];
USE [SEL]; GRANT SELECT ON sys.views TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_indexes TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_attributes TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_collections TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_component_placements TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_components TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_elements TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_facets TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_model_groups TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_namespaces TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_types TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_wildcard_namespaces TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_wildcards TO [public];