USE [SEL]; CREATE USER [amsa\SQL_STA_SEL_Write] FROM LOGIN [amsa\SQL_STA_SEL_Write];
USE [SEL]; CREATE USER [amsa\SQL_TST_SEL_Read] FROM LOGIN [amsa\SQL_TST_SEL_Read];
USE [SEL]; CREATE USER [AMSA\svtstcontactvalidate] FROM LOGIN [AMSA\svtstcontactvalidate] WITH DEFAULT_SCHEMA = [dbo];
USE [SEL]; CREATE USER [AMSA\svtstLoan] FROM LOGIN [AMSA\svtstLoan] WITH DEFAULT_SCHEMA = [dbo];
USE [SEL]; CREATE USER [AMSA\svtstLoanMgt] FROM LOGIN [AMSA\svtstLoanMgt] WITH DEFAULT_SCHEMA = [dbo];
USE [SEL]; CREATE USER [AMSA\svtstperson] FROM LOGIN [AMSA\svtstperson] WITH DEFAULT_SCHEMA = [dbo];
USE [SEL]; CREATE USER [AMSA\svtstpersonmgt] FROM LOGIN [AMSA\svtstpersonmgt] WITH DEFAULT_SCHEMA = [dbo];
USE [SEL]; CREATE USER [AMSA\svtstRefData] FROM LOGIN [AMSA\svtstRefData] WITH DEFAULT_SCHEMA = [dbo];
USE [SEL]; CREATE USER [AMSA\svtstserviceadapter] FROM LOGIN [AMSA\svtstserviceadapter] WITH DEFAULT_SCHEMA = [dbo];
USE [SEL]; CREATE USER [DBTKUSER] FOR LOGIN [DBTKUSER] WITH DEFAULT_SCHEMA = [dbo];

--
--
EXEC dbo.sp_addsrvrolemember 'ATSTDBS010\SQLServer2005MSSQLUser$ATSTDBS010$SEL', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'ATSTDBS010\SQLServer2005SQLAgentUser$ATSTDBS010$SEL', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\prodDBA', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'DBTKUSER', 'bulkadmin';
EXEC [SEL].dbo.sp_addrolemember 'db_owner', 'DBTKUSER';
EXEC [SEL].dbo.sp_addrolemember 'db_datareader', 'AMSA\svtstcontactvalidate';
EXEC [SEL].dbo.sp_addrolemember 'db_datareader', 'AMSA\svtstLoan';
EXEC [SEL].dbo.sp_addrolemember 'db_datareader', 'AMSA\svtstperson';
EXEC [SEL].dbo.sp_addrolemember 'db_datareader', 'AMSA\svtstRefData';
EXEC [SEL].dbo.sp_addrolemember 'db_datareader', 'AMSA\svtstserviceadapter';
EXEC [SEL].dbo.sp_addrolemember 'db_datareader', 'AMSA\svtstpersonmgt';
EXEC [SEL].dbo.sp_addrolemember 'db_datareader', 'AMSA\svtstLoanMgt';
EXEC [SEL].dbo.sp_addrolemember 'db_datareader', 'amsa\SQL_TST_SEL_Read';
EXEC [SEL].dbo.sp_addrolemember 'db_datawriter', 'amsa\SQL_STA_SEL_Write';

--
USE master; GRANT CONNECT SQL TO [AMSA\prodDBA];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_STA_SEL_Write];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_TST_SEL_Read];
USE master; GRANT CONNECT SQL TO [AMSA\svtstcontactvalidate];
USE master; GRANT CONNECT SQL TO [AMSA\svtstLoan];
USE master; GRANT CONNECT SQL TO [AMSA\svtstLoanMgt];
USE master; GRANT CONNECT SQL TO [AMSA\svtstperson];
USE master; GRANT CONNECT SQL TO [AMSA\svtstpersonmgt];
USE master; GRANT CONNECT SQL TO [AMSA\svtstRefData];
USE master; GRANT CONNECT SQL TO [AMSA\svtstserviceadapter];
--
USE master; GRANT CONNECT SQL TO [ATSTDBS010\SQLServer2005MSFTEUser$ATSTDBS010$SEL];
USE master; GRANT CONNECT SQL TO [ATSTDBS010\SQLServer2005MSSQLUser$ATSTDBS010$SEL];
USE master; GRANT CONNECT SQL TO [ATSTDBS010\SQLServer2005SQLAgentUser$ATSTDBS010$SEL];
USE master; GRANT CONNECT SQL TO [DBTKUSER];
USE master; GRANT CONNECT SQL TO [NT AUTHORITY\SYSTEM];
USE master; GRANT VIEW ANY DATABASE TO [public];
USE [SEL]; GRANT CONNECT TO [amsa\SQL_STA_SEL_Write];
USE [SEL]; GRANT CONNECT TO [amsa\SQL_TST_SEL_Read];
USE [SEL]; GRANT CONNECT TO [AMSA\svtstcontactvalidate];
USE [SEL]; GRANT CONNECT TO [AMSA\svtstLoan];
USE [SEL]; GRANT CONNECT TO [AMSA\svtstLoanMgt];
USE [SEL]; GRANT CONNECT TO [AMSA\svtstperson];
USE [SEL]; GRANT CONNECT TO [AMSA\svtstpersonmgt];
USE [SEL]; GRANT CONNECT TO [AMSA\svtstRefData];
USE [SEL]; GRANT CONNECT TO [AMSA\svtstserviceadapter];
--
USE [SEL]; GRANT CONNECT TO [DBTKUSER];
USE [SEL]; GRANT SELECT ON sys.all_columns TO [public];
USE [SEL]; GRANT SELECT ON sys.all_objects TO [public];
USE [SEL]; GRANT SELECT ON sys.all_parameters TO [public];
USE [SEL]; GRANT SELECT ON sys.all_sql_modules TO [public];
USE [SEL]; GRANT SELECT ON sys.all_views TO [public];
USE [SEL]; GRANT SELECT ON sys.allocation_units TO [public];
USE [SEL]; GRANT SELECT ON sys.assemblies TO [public];
USE [SEL]; GRANT SELECT ON sys.assembly_files TO [public];
USE [SEL]; GRANT SELECT ON sys.assembly_modules TO [public];
USE [SEL]; GRANT SELECT ON sys.assembly_references TO [public];
USE [SEL]; GRANT SELECT ON sys.assembly_types TO [public];
USE [SEL]; GRANT SELECT ON sys.asymmetric_keys TO [public];
USE [SEL]; GRANT SELECT ON sys.certificates TO [public];
USE [SEL]; GRANT SELECT ON sys.check_constraints TO [public];
USE [SEL]; GRANT SELECT ON sys.column_type_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.column_xml_schema_collection_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.columns TO [public];
USE [SEL]; GRANT SELECT ON sys.computed_columns TO [public];
USE [SEL]; GRANT SELECT ON sys.conversation_endpoints TO [public];
USE [SEL]; GRANT SELECT ON sys.conversation_groups TO [public];
USE [SEL]; GRANT SELECT ON sys.crypt_properties TO [public];
USE [SEL]; GRANT SELECT ON sys.data_spaces TO [public];
USE [SEL]; GRANT SELECT ON sys.database_files TO [public];
USE [SEL]; GRANT SELECT ON sys.database_permissions TO [public];
USE [SEL]; GRANT SELECT ON sys.database_principal_aliases TO [public];
USE [SEL]; GRANT SELECT ON sys.database_principals TO [public];
USE [SEL]; GRANT SELECT ON sys.database_role_members TO [public];
USE [SEL]; GRANT SELECT ON sys.default_constraints TO [public];
USE [SEL]; GRANT SELECT ON sys.destination_data_spaces TO [public];
USE [SEL]; GRANT SELECT ON sys.event_notifications TO [public];
USE [SEL]; GRANT SELECT ON sys.events TO [public];
USE [SEL]; GRANT SELECT ON sys.extended_procedures TO [public];
USE [SEL]; GRANT SELECT ON sys.extended_properties TO [public];
USE [SEL]; GRANT SELECT ON sys.filegroups TO [public];
USE [SEL]; GRANT SELECT ON sys.foreign_key_columns TO [public];
USE [SEL]; GRANT SELECT ON sys.foreign_keys TO [public];
USE [SEL]; GRANT SELECT ON sys.fulltext_catalogs TO [public];
USE [SEL]; GRANT SELECT ON sys.fulltext_index_catalog_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.fulltext_index_columns TO [public];
USE [SEL]; GRANT SELECT ON sys.fulltext_indexes TO [public];
USE [SEL]; GRANT SELECT ON sys.identity_columns TO [public];
USE [SEL]; GRANT SELECT ON sys.index_columns TO [public];
USE [SEL]; GRANT SELECT ON sys.indexes TO [public];
USE [SEL]; GRANT SELECT ON sys.internal_tables TO [public];
USE [SEL]; GRANT SELECT ON sys.key_constraints TO [public];
USE [SEL]; GRANT SELECT ON sys.key_encryptions TO [public];
USE [SEL]; GRANT SELECT ON sys.message_type_xml_schema_collection_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.module_assembly_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.numbered_procedure_parameters TO [public];
USE [SEL]; GRANT SELECT ON sys.numbered_procedures TO [public];
USE [SEL]; GRANT SELECT ON sys.objects TO [public];
USE [SEL]; GRANT SELECT ON sys.parameter_type_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.parameter_xml_schema_collection_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.parameters TO [public];
USE [SEL]; GRANT SELECT ON sys.partition_functions TO [public];
USE [SEL]; GRANT SELECT ON sys.partition_parameters TO [public];
USE [SEL]; GRANT SELECT ON sys.partition_range_values TO [public];
USE [SEL]; GRANT SELECT ON sys.partition_schemes TO [public];
USE [SEL]; GRANT SELECT ON sys.partitions TO [public];
USE [SEL]; GRANT SELECT ON sys.plan_guides TO [public];
USE [SEL]; GRANT SELECT ON sys.procedures TO [public];
USE [SEL]; GRANT SELECT ON sys.remote_service_bindings TO [public];
USE [SEL]; GRANT SELECT ON sys.routes TO [public];
USE [SEL]; GRANT SELECT ON sys.schemas TO [public];
USE [SEL]; GRANT SELECT ON sys.service_contract_message_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.service_contract_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.service_contracts TO [public];
USE [SEL]; GRANT SELECT ON sys.service_message_types TO [public];
USE [SEL]; GRANT SELECT ON sys.service_queue_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.service_queues TO [public];
USE [SEL]; GRANT SELECT ON sys.services TO [public];
USE [SEL]; GRANT SELECT ON sys.sql_dependencies TO [public];
USE [SEL]; GRANT SELECT ON sys.sql_modules TO [public];
USE [SEL]; GRANT SELECT ON sys.stats TO [public];
USE [SEL]; GRANT SELECT ON sys.stats_columns TO [public];
USE [SEL]; GRANT SELECT ON sys.symmetric_keys TO [public];
USE [SEL]; GRANT SELECT ON sys.synonyms TO [public];
USE [SEL]; GRANT SELECT ON sys.syscolumns TO [public];
USE [SEL]; GRANT SELECT ON sys.syscomments TO [public];
USE [SEL]; GRANT SELECT ON sys.sysconstraints TO [public];
USE [SEL]; GRANT SELECT ON sys.sysdepends TO [public];
USE [SEL]; GRANT SELECT ON sys.sysfilegroups TO [public];
USE [SEL]; GRANT SELECT ON sys.sysfiles TO [public];
USE [SEL]; GRANT SELECT ON sys.sysforeignkeys TO [public];
USE [SEL]; GRANT SELECT ON sys.sysfulltextcatalogs TO [public];
USE [SEL]; GRANT SELECT ON sys.sysindexes TO [public];
USE [SEL]; GRANT SELECT ON sys.sysindexkeys TO [public];
USE [SEL]; GRANT SELECT ON sys.sysmembers TO [public];
USE [SEL]; GRANT SELECT ON sys.sysobjects TO [public];
USE [SEL]; GRANT SELECT ON sys.syspermissions TO [public];
USE [SEL]; GRANT SELECT ON sys.sysprotects TO [public];
USE [SEL]; GRANT SELECT ON sys.sysreferences TO [public];
USE [SEL]; GRANT SELECT ON sys.syssegments TO [public];
USE [SEL]; GRANT SELECT ON sys.system_columns TO [public];
USE [SEL]; GRANT SELECT ON sys.system_objects TO [public];
USE [SEL]; GRANT SELECT ON sys.system_parameters TO [public];
USE [SEL]; GRANT SELECT ON sys.system_sql_modules TO [public];
USE [SEL]; GRANT SELECT ON sys.system_views TO [public];
USE [SEL]; GRANT SELECT ON sys.systypes TO [public];
USE [SEL]; GRANT SELECT ON sys.sysusers TO [public];
USE [SEL]; GRANT SELECT ON sys.tables TO [public];
USE [SEL]; GRANT SELECT ON sys.transmission_queue TO [public];
USE [SEL]; GRANT SELECT ON sys.trigger_events TO [public];
USE [SEL]; GRANT SELECT ON sys.triggers TO [public];
USE [SEL]; GRANT SELECT ON sys.type_assembly_usages TO [public];
USE [SEL]; GRANT SELECT ON sys.types TO [public];
USE [SEL]; GRANT SELECT ON sys.views TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_indexes TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_attributes TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_collections TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_component_placements TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_components TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_elements TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_facets TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_model_groups TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_namespaces TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_types TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_wildcard_namespaces TO [public];
USE [SEL]; GRANT SELECT ON sys.xml_schema_wildcards TO [public];