USE [BOWS]; CREATE USER [AMSA\SAS Server Users] FROM LOGIN [AMSA\SAS Server Users];
USE [BOWS]; CREATE USER [amsa\sql_prd_reader] FROM LOGIN [amsa\sql_prd_reader];
USE [BOWS]; CREATE USER [AMSA\SQL_STA_Reader] FROM LOGIN [AMSA\SQL_STA_Reader];
USE [BOWS]; CREATE USER [AMSA\SvProdSQLDBExec] FROM LOGIN [AMSA\SvProdSQLDBExec] WITH DEFAULT_SCHEMA = [dbo];
USE [BOWS]; CREATE USER [AMSA\svstafileutility] FROM LOGIN [AMSA\svstafileutility] WITH DEFAULT_SCHEMA = [dbo];
USE [BOWS]; CREATE USER [AMSA\svstasqlagentexec] FROM LOGIN [AMSA\svstasqlagentexec] WITH DEFAULT_SCHEMA = [dbo];
USE [BOWS]; CREATE USER [DBTKUser] FOR LOGIN [DBTKUser] WITH DEFAULT_SCHEMA = [dbo];
USE [BOWS]; CREATE USER [teamworks] FOR LOGIN [teamworks] WITH DEFAULT_SCHEMA = [dbo];

--
--
EXEC dbo.sp_addsrvrolemember 'AMSA\SQL Cluster STA Server Service Group', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\SQL Cluster STA Agent Service Group', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\ProdDBA', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\DLake', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\TTrent', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svStaWinCluster', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svstasqlagentexec', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svstafileutility', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svstasqldbexec', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'DBTKUser', 'bulkadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svstafileutility', 'bulkadmin';
EXEC [BOWS].dbo.sp_addrolemember 'db_owner', 'DBTKUser';
EXEC [BOWS].dbo.sp_addrolemember 'db_owner', 'teamworks';
EXEC [BOWS].dbo.sp_addrolemember 'db_owner', 'AMSA\SvProdSQLDBExec';
EXEC [BOWS].dbo.sp_addrolemember 'db_owner', 'AMSA\svstafileutility';
EXEC [BOWS].dbo.sp_addrolemember 'db_owner', 'AMSA\svstasqlagentexec';
EXEC [BOWS].dbo.sp_addrolemember 'db_datareader', 'amsa\sql_prd_reader';
EXEC [BOWS].dbo.sp_addrolemember 'db_datareader', 'AMSA\SAS Server Users';
EXEC [BOWS].dbo.sp_addrolemember 'db_datareader', 'AMSA\SQL_STA_Reader';

USE master; GRANT ADMINISTER BULK OPERATIONS TO [AMSA\svstafileutility];
USE master; GRANT ADMINISTER BULK OPERATIONS TO [DBTKUser];
USE master; GRANT ADMINISTER BULK OPERATIONS TO [teamworks];
--
USE master; GRANT CONNECT SQL TO [AMSA\bdanrel];
USE master; GRANT CONNECT SQL TO [AMSA\DLake];
USE master; GRANT CONNECT SQL TO [AMSA\estorey];
USE master; GRANT CONNECT SQL TO [AMSA\mamante];
USE master; GRANT CONNECT SQL TO [AMSA\ProdDBA];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Agent Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Full Text Search Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Server Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_STA_Reader];
USE master; GRANT CONNECT SQL TO [AMSA\SSRSReportViewer];
USE master; GRANT CONNECT SQL TO [AMSA\svstafileutility];
USE master; GRANT CONNECT SQL TO [AMSA\svstasqlagentexec];
USE master; GRANT CONNECT SQL TO [AMSA\svstasqldbexec];
USE master; GRANT CONNECT SQL TO [AMSA\SvStaSSRSExec];
USE master; GRANT CONNECT SQL TO [AMSA\svStaWinCluster];
USE master; GRANT CONNECT SQL TO [AMSA\TTrent];
--
USE master; GRANT CONNECT SQL TO [DBTKUser];
USE master; GRANT CONNECT SQL TO [NT AUTHORITY\SYSTEM];
USE master; GRANT CONNECT SQL TO [SvStaMonOSS];
USE master; GRANT CONNECT SQL TO [teamworks];
USE master; GRANT VIEW ANY DATABASE TO [public];
USE [BOWS]; GRANT ALTER ON SCHEMA::dbo TO [AMSA\svstafileutility];
USE [BOWS]; GRANT CONNECT TO [AMSA\SAS Server Users];
USE [BOWS]; GRANT CONNECT TO [amsa\sql_prd_reader];
USE [BOWS]; GRANT CONNECT TO [AMSA\SQL_STA_Reader];
USE [BOWS]; GRANT CONNECT TO [AMSA\SvProdSQLDBExec];
USE [BOWS]; GRANT CONNECT TO [AMSA\svstafileutility];
USE [BOWS]; GRANT CONNECT TO [AMSA\svstasqlagentexec];
--
USE [BOWS]; GRANT CONNECT TO [DBTKUser];
USE [BOWS]; GRANT CONNECT TO [teamworks];
USE [BOWS]; GRANT DELETE ON SCHEMA::dbo TO [AMSA\svstafileutility];
USE [BOWS]; GRANT EXECUTE ON SCHEMA::dbo TO [AMSA\svstafileutility];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_AUD_ETL_Insert TO [AMSA\svstafileutility];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_CampaignCommunicationInfo TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_CampaignEmailOutbound TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_CampaignEmailSeeds TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_ExternalData_PostProcess TO [AMSA\svstafileutility];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_ExternalData_PreProcess TO [AMSA\svstafileutility];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_ExternalData_Process TO [AMSA\svstafileutility];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_GetCampaignInfo TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_GetCandidateBorrowerListForAutodialer TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_InsertCMPCampaignInstance TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_InsertCMPCampaignInstanceActivity TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_InsertCMPCampaignNewsletterSubscription TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_InsertCOMCommunication TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_InsertCOMCommunicationByEmail TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_InsertCOMCommunicationByFax TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_InsertCOMCommunicationByMail TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_InsertCOMCommunicationByPhone TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_InsertCOMCommunicationCollateralRequest TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_InsertCOMCommunicationRowsByEmail TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_InsertCOMCommunicationRowsByMail TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_InsertCOMWellnessResponse TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_LoadJourneyData TO [AMSA\svstafileutility];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_LoadMOTFromStagingToTarget TO [AMSA\svstafileutility];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_TranscontinentalOutbound TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_UpdateCMPCampaignInstance TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_UpdateCMPCampaignInstanceActivity TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_ValidateAndPocessCampaignEmailInbound TO [AMSA\svstafileutility];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_ValidateAndPocessJourneyAutodialerFile TO [AMSA\svstafileutility];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_ValidateAndPocessJourneyMainSAS TO [AMSA\svstafileutility];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_ValidateAndPocessJourneyNewsletter TO [AMSA\svstafileutility];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_ValidateAndPocessJourneySolutionsKit TO [AMSA\svstafileutility];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_ValidateAndPocessTransitionSAS TO [AMSA\svstafileutility];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_ValidateAndPocessTransitionsExport TO [AMSA\svstafileutility];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_ValidateAndProcessAfterCureSAS TO [teamworks];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_ValidateAndProcessMOTAccountSAS TO [AMSA\svstafileutility];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_ValidateAndProcessMOTBorrowerSAS TO [AMSA\svstafileutility];
USE [BOWS]; GRANT EXECUTE ON dbo.bows_ValidateAndProcessSilverPopInbound TO [AMSA\svstafileutility];
USE [BOWS]; GRANT INSERT ON SCHEMA::dbo TO [AMSA\svstafileutility];
USE [BOWS]; GRANT SELECT ON SCHEMA::dbo TO [AMSA\svstafileutility];
USE [BOWS]; GRANT SELECT ON sys.all_columns TO [public];
USE [BOWS]; GRANT SELECT ON sys.all_objects TO [public];
USE [BOWS]; GRANT SELECT ON sys.all_parameters TO [public];
USE [BOWS]; GRANT SELECT ON sys.all_sql_modules TO [public];
USE [BOWS]; GRANT SELECT ON sys.all_views TO [public];
USE [BOWS]; GRANT SELECT ON sys.allocation_units TO [public];
USE [BOWS]; GRANT SELECT ON sys.assemblies TO [public];
USE [BOWS]; GRANT SELECT ON sys.assembly_files TO [public];
USE [BOWS]; GRANT SELECT ON sys.assembly_modules TO [public];
USE [BOWS]; GRANT SELECT ON sys.assembly_references TO [public];
USE [BOWS]; GRANT SELECT ON sys.assembly_types TO [public];
USE [BOWS]; GRANT SELECT ON sys.asymmetric_keys TO [public];
USE [BOWS]; GRANT SELECT ON sys.certificates TO [public];
USE [BOWS]; GRANT SELECT ON sys.check_constraints TO [public];
USE [BOWS]; GRANT SELECT ON sys.column_type_usages TO [public];
USE [BOWS]; GRANT SELECT ON sys.column_xml_schema_collection_usages TO [public];
USE [BOWS]; GRANT SELECT ON sys.columns TO [public];
USE [BOWS]; GRANT SELECT ON sys.computed_columns TO [public];
USE [BOWS]; GRANT SELECT ON sys.conversation_endpoints TO [public];
USE [BOWS]; GRANT SELECT ON sys.conversation_groups TO [public];
USE [BOWS]; GRANT SELECT ON sys.crypt_properties TO [public];
USE [BOWS]; GRANT SELECT ON sys.data_spaces TO [public];
USE [BOWS]; GRANT SELECT ON sys.database_files TO [public];
USE [BOWS]; GRANT SELECT ON sys.database_permissions TO [public];
USE [BOWS]; GRANT SELECT ON sys.database_principal_aliases TO [public];
USE [BOWS]; GRANT SELECT ON sys.database_principals TO [public];
USE [BOWS]; GRANT SELECT ON sys.database_role_members TO [public];
USE [BOWS]; GRANT SELECT ON sys.default_constraints TO [public];
USE [BOWS]; GRANT SELECT ON sys.destination_data_spaces TO [public];
USE [BOWS]; GRANT SELECT ON sys.event_notifications TO [public];
USE [BOWS]; GRANT SELECT ON sys.events TO [public];
USE [BOWS]; GRANT SELECT ON sys.extended_procedures TO [public];
USE [BOWS]; GRANT SELECT ON sys.extended_properties TO [public];
USE [BOWS]; GRANT SELECT ON sys.filegroups TO [public];
USE [BOWS]; GRANT SELECT ON sys.foreign_key_columns TO [public];
USE [BOWS]; GRANT SELECT ON sys.foreign_keys TO [public];
USE [BOWS]; GRANT SELECT ON sys.fulltext_catalogs TO [public];
USE [BOWS]; GRANT SELECT ON sys.fulltext_index_catalog_usages TO [public];
USE [BOWS]; GRANT SELECT ON sys.fulltext_index_columns TO [public];
USE [BOWS]; GRANT SELECT ON sys.fulltext_indexes TO [public];
USE [BOWS]; GRANT SELECT ON sys.identity_columns TO [public];
USE [BOWS]; GRANT SELECT ON sys.index_columns TO [public];
USE [BOWS]; GRANT SELECT ON sys.indexes TO [public];
USE [BOWS]; GRANT SELECT ON sys.internal_tables TO [public];
USE [BOWS]; GRANT SELECT ON sys.key_constraints TO [public];
USE [BOWS]; GRANT SELECT ON sys.key_encryptions TO [public];
USE [BOWS]; GRANT SELECT ON sys.message_type_xml_schema_collection_usages TO [public];
USE [BOWS]; GRANT SELECT ON sys.module_assembly_usages TO [public];
USE [BOWS]; GRANT SELECT ON sys.numbered_procedure_parameters TO [public];
USE [BOWS]; GRANT SELECT ON sys.numbered_procedures TO [public];
USE [BOWS]; GRANT SELECT ON sys.objects TO [public];
USE [BOWS]; GRANT SELECT ON sys.parameter_type_usages TO [public];
USE [BOWS]; GRANT SELECT ON sys.parameter_xml_schema_collection_usages TO [public];
USE [BOWS]; GRANT SELECT ON sys.parameters TO [public];
USE [BOWS]; GRANT SELECT ON sys.partition_functions TO [public];
USE [BOWS]; GRANT SELECT ON sys.partition_parameters TO [public];
USE [BOWS]; GRANT SELECT ON sys.partition_range_values TO [public];
USE [BOWS]; GRANT SELECT ON sys.partition_schemes TO [public];
USE [BOWS]; GRANT SELECT ON sys.partitions TO [public];
USE [BOWS]; GRANT SELECT ON sys.plan_guides TO [public];
USE [BOWS]; GRANT SELECT ON sys.procedures TO [public];
USE [BOWS]; GRANT SELECT ON sys.remote_service_bindings TO [public];
USE [BOWS]; GRANT SELECT ON sys.routes TO [public];
USE [BOWS]; GRANT SELECT ON sys.schemas TO [public];
USE [BOWS]; GRANT SELECT ON sys.service_contract_message_usages TO [public];
USE [BOWS]; GRANT SELECT ON sys.service_contract_usages TO [public];
USE [BOWS]; GRANT SELECT ON sys.service_contracts TO [public];
USE [BOWS]; GRANT SELECT ON sys.service_message_types TO [public];
USE [BOWS]; GRANT SELECT ON sys.service_queue_usages TO [public];
USE [BOWS]; GRANT SELECT ON sys.service_queues TO [public];
USE [BOWS]; GRANT SELECT ON sys.services TO [public];
USE [BOWS]; GRANT SELECT ON sys.sql_dependencies TO [public];
USE [BOWS]; GRANT SELECT ON sys.sql_modules TO [public];
USE [BOWS]; GRANT SELECT ON sys.stats TO [public];
USE [BOWS]; GRANT SELECT ON sys.stats_columns TO [public];
USE [BOWS]; GRANT SELECT ON sys.symmetric_keys TO [public];
USE [BOWS]; GRANT SELECT ON sys.synonyms TO [public];
USE [BOWS]; GRANT SELECT ON sys.syscolumns TO [public];
USE [BOWS]; GRANT SELECT ON sys.syscomments TO [public];
USE [BOWS]; GRANT SELECT ON sys.sysconstraints TO [public];
USE [BOWS]; GRANT SELECT ON sys.sysdepends TO [public];
USE [BOWS]; GRANT SELECT ON sys.sysfilegroups TO [public];
USE [BOWS]; GRANT SELECT ON sys.sysfiles TO [public];
USE [BOWS]; GRANT SELECT ON sys.sysforeignkeys TO [public];
USE [BOWS]; GRANT SELECT ON sys.sysfulltextcatalogs TO [public];
USE [BOWS]; GRANT SELECT ON sys.sysindexes TO [public];
USE [BOWS]; GRANT SELECT ON sys.sysindexkeys TO [public];
USE [BOWS]; GRANT SELECT ON sys.sysmembers TO [public];
USE [BOWS]; GRANT SELECT ON sys.sysobjects TO [public];
USE [BOWS]; GRANT SELECT ON sys.syspermissions TO [public];
USE [BOWS]; GRANT SELECT ON sys.sysprotects TO [public];
USE [BOWS]; GRANT SELECT ON sys.sysreferences TO [public];
USE [BOWS]; GRANT SELECT ON sys.syssegments TO [public];
USE [BOWS]; GRANT SELECT ON sys.system_columns TO [public];
USE [BOWS]; GRANT SELECT ON sys.system_objects TO [public];
USE [BOWS]; GRANT SELECT ON sys.system_parameters TO [public];
USE [BOWS]; GRANT SELECT ON sys.system_sql_modules TO [public];
USE [BOWS]; GRANT SELECT ON sys.system_views TO [public];
USE [BOWS]; GRANT SELECT ON sys.systypes TO [public];
USE [BOWS]; GRANT SELECT ON sys.sysusers TO [public];
USE [BOWS]; GRANT SELECT ON sys.tables TO [public];
USE [BOWS]; GRANT SELECT ON sys.transmission_queue TO [public];
USE [BOWS]; GRANT SELECT ON sys.trigger_events TO [public];
USE [BOWS]; GRANT SELECT ON sys.triggers TO [public];
USE [BOWS]; GRANT SELECT ON sys.type_assembly_usages TO [public];
USE [BOWS]; GRANT SELECT ON sys.types TO [public];
USE [BOWS]; GRANT SELECT ON sys.views TO [public];
USE [BOWS]; GRANT SELECT ON sys.xml_indexes TO [public];
USE [BOWS]; GRANT SELECT ON sys.xml_schema_attributes TO [public];
USE [BOWS]; GRANT SELECT ON sys.xml_schema_collections TO [public];
USE [BOWS]; GRANT SELECT ON sys.xml_schema_component_placements TO [public];
USE [BOWS]; GRANT SELECT ON sys.xml_schema_components TO [public];
USE [BOWS]; GRANT SELECT ON sys.xml_schema_elements TO [public];
USE [BOWS]; GRANT SELECT ON sys.xml_schema_facets TO [public];
USE [BOWS]; GRANT SELECT ON sys.xml_schema_model_groups TO [public];
USE [BOWS]; GRANT SELECT ON sys.xml_schema_namespaces TO [public];
USE [BOWS]; GRANT SELECT ON sys.xml_schema_types TO [public];
USE [BOWS]; GRANT SELECT ON sys.xml_schema_wildcard_namespaces TO [public];
USE [BOWS]; GRANT SELECT ON sys.xml_schema_wildcards TO [public];
USE [BOWS]; GRANT UPDATE ON SCHEMA::dbo TO [AMSA\svstafileutility];
USE [BOWS]; GRANT VIEW DEFINITION TO [AMSA\SQL_STA_Reader];
-----------------------------------------------------------------------------------------------------

USE [MCDB]; CREATE USER [AMSA\SAS Server Users] FROM LOGIN [AMSA\SAS Server Users];
USE [MCDB]; CREATE USER [amsa\sql_prd_reader] FROM LOGIN [amsa\sql_prd_reader];
USE [MCDB]; CREATE USER [AMSA\SQL_STA_Reader] FROM LOGIN [AMSA\SQL_STA_Reader];
USE [MCDB]; CREATE USER [AMSA\SSRSReportViewer] FROM LOGIN [AMSA\SSRSReportViewer];
USE [MCDB]; CREATE USER [amsa\svprodsqlagentexec] FROM LOGIN [amsa\svprodsqlagentexec] WITH DEFAULT_SCHEMA = [dbo];
USE [MCDB]; CREATE USER [AMSA\SvProdSQLDBExec] FROM LOGIN [AMSA\SvProdSQLDBExec] WITH DEFAULT_SCHEMA = [dbo];
USE [MCDB]; CREATE USER [AMSA\SVPRODSSRSEXEC] FROM LOGIN [AMSA\SVPRODSSRSEXEC] WITH DEFAULT_SCHEMA = [dbo];
USE [MCDB]; CREATE USER [AMSA\svstasqlagentexec] FROM LOGIN [AMSA\svstasqlagentexec] WITH DEFAULT_SCHEMA = [dbo];
USE [MCDB]; CREATE USER [amsa\SvStaSSRSExec] FROM LOGIN [amsa\SvStaSSRSExec] WITH DEFAULT_SCHEMA = [dbo];
USE [MCDB]; CREATE USER [DBTKUser] FOR LOGIN [DBTKUser] WITH DEFAULT_SCHEMA = [dbo];
USE [MCDB]; CREATE USER [teamworks] FOR LOGIN [teamworks] WITH DEFAULT_SCHEMA = [dbo];

--
--
EXEC dbo.sp_addsrvrolemember 'AMSA\SQL Cluster STA Server Service Group', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\SQL Cluster STA Agent Service Group', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\ProdDBA', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\DLake', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\TTrent', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svStaWinCluster', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svstasqlagentexec', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svstafileutility', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svstasqldbexec', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'DBTKUser', 'bulkadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svstafileutility', 'bulkadmin';
EXEC [MCDB].dbo.sp_addrolemember 'db_owner', 'teamworks';
EXEC [MCDB].dbo.sp_addrolemember 'db_owner', 'amsa\svprodsqlagentexec';
EXEC [MCDB].dbo.sp_addrolemember 'db_owner', 'AMSA\SvProdSQLDBExec';
EXEC [MCDB].dbo.sp_addrolemember 'db_owner', 'AMSA\svstasqlagentexec';
EXEC [MCDB].dbo.sp_addrolemember 'db_datareader', 'DBTKUser';
EXEC [MCDB].dbo.sp_addrolemember 'db_datareader', 'amsa\sql_prd_reader';
EXEC [MCDB].dbo.sp_addrolemember 'db_datareader', 'teamworks';
EXEC [MCDB].dbo.sp_addrolemember 'db_datareader', 'AMSA\SAS Server Users';
EXEC [MCDB].dbo.sp_addrolemember 'db_datareader', 'AMSA\SQL_STA_Reader';
EXEC [MCDB].dbo.sp_addrolemember 'db_datareader', 'AMSA\SSRSReportViewer';
EXEC [MCDB].dbo.sp_addrolemember 'db_datawriter', 'teamworks';

USE master; GRANT ADMINISTER BULK OPERATIONS TO [AMSA\svstafileutility];
USE master; GRANT ADMINISTER BULK OPERATIONS TO [DBTKUser];
USE master; GRANT ADMINISTER BULK OPERATIONS TO [teamworks];
--
USE master; GRANT CONNECT SQL TO [AMSA\bdanrel];
USE master; GRANT CONNECT SQL TO [AMSA\DLake];
USE master; GRANT CONNECT SQL TO [AMSA\estorey];
USE master; GRANT CONNECT SQL TO [AMSA\mamante];
USE master; GRANT CONNECT SQL TO [AMSA\ProdDBA];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Agent Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Full Text Search Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Server Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_STA_Reader];
USE master; GRANT CONNECT SQL TO [AMSA\SSRSReportViewer];
USE master; GRANT CONNECT SQL TO [AMSA\svstafileutility];
USE master; GRANT CONNECT SQL TO [AMSA\svstasqlagentexec];
USE master; GRANT CONNECT SQL TO [AMSA\svstasqldbexec];
USE master; GRANT CONNECT SQL TO [AMSA\SvStaSSRSExec];
USE master; GRANT CONNECT SQL TO [AMSA\svStaWinCluster];
USE master; GRANT CONNECT SQL TO [AMSA\TTrent];
--
USE master; GRANT CONNECT SQL TO [DBTKUser];
USE master; GRANT CONNECT SQL TO [NT AUTHORITY\SYSTEM];
USE master; GRANT CONNECT SQL TO [SvStaMonOSS];
USE master; GRANT CONNECT SQL TO [teamworks];
USE master; GRANT VIEW ANY DATABASE TO [public];
USE [MCDB]; GRANT CONNECT TO [AMSA\SAS Server Users];
USE [MCDB]; GRANT CONNECT TO [amsa\sql_prd_reader];
USE [MCDB]; GRANT CONNECT TO [AMSA\SQL_STA_Reader];
USE [MCDB]; GRANT CONNECT TO [AMSA\SSRSReportViewer];
USE [MCDB]; GRANT CONNECT TO [amsa\svprodsqlagentexec];
USE [MCDB]; GRANT CONNECT TO [AMSA\SvProdSQLDBExec];
USE [MCDB]; GRANT CONNECT TO [AMSA\SVPRODSSRSEXEC];
USE [MCDB]; GRANT CONNECT TO [AMSA\svstasqlagentexec];
USE [MCDB]; GRANT CONNECT TO [amsa\SvStaSSRSExec];
--
USE [MCDB]; GRANT CONNECT TO [DBTKUser];
USE [MCDB]; GRANT CONNECT TO [teamworks];
USE [MCDB]; GRANT EXECUTE ON SCHEMA::dbo TO [AMSA\SVPRODSSRSEXEC];
USE [MCDB]; GRANT EXECUTE ON SCHEMA::dbo TO [amsa\SvStaSSRSExec];
USE [MCDB]; GRANT EXECUTE ON dbo.mcsp_GetExactPersonInfo TO [teamworks];
USE [MCDB]; GRANT EXECUTE ON dbo.mcsp_InitialPersonSearch TO [teamworks];
USE [MCDB]; GRANT SELECT ON SCHEMA::dbo TO [AMSA\SVPRODSSRSEXEC];
USE [MCDB]; GRANT SELECT ON SCHEMA::dbo TO [amsa\SvStaSSRSExec];
USE [MCDB]; GRANT SELECT ON sys.all_columns TO [public];
USE [MCDB]; GRANT SELECT ON sys.all_objects TO [public];
USE [MCDB]; GRANT SELECT ON sys.all_parameters TO [public];
USE [MCDB]; GRANT SELECT ON sys.all_sql_modules TO [public];
USE [MCDB]; GRANT SELECT ON sys.all_views TO [public];
USE [MCDB]; GRANT SELECT ON sys.allocation_units TO [public];
USE [MCDB]; GRANT SELECT ON sys.assemblies TO [public];
USE [MCDB]; GRANT SELECT ON sys.assembly_files TO [public];
USE [MCDB]; GRANT SELECT ON sys.assembly_modules TO [public];
USE [MCDB]; GRANT SELECT ON sys.assembly_references TO [public];
USE [MCDB]; GRANT SELECT ON sys.assembly_types TO [public];
USE [MCDB]; GRANT SELECT ON sys.asymmetric_keys TO [public];
USE [MCDB]; GRANT SELECT ON sys.certificates TO [public];
USE [MCDB]; GRANT SELECT ON sys.check_constraints TO [public];
USE [MCDB]; GRANT SELECT ON sys.column_type_usages TO [public];
USE [MCDB]; GRANT SELECT ON sys.column_xml_schema_collection_usages TO [public];
USE [MCDB]; GRANT SELECT ON sys.columns TO [public];
USE [MCDB]; GRANT SELECT ON sys.computed_columns TO [public];
USE [MCDB]; GRANT SELECT ON sys.conversation_endpoints TO [public];
USE [MCDB]; GRANT SELECT ON sys.conversation_groups TO [public];
USE [MCDB]; GRANT SELECT ON sys.crypt_properties TO [public];
USE [MCDB]; GRANT SELECT ON sys.data_spaces TO [public];
USE [MCDB]; GRANT SELECT ON sys.database_files TO [public];
USE [MCDB]; GRANT SELECT ON sys.database_permissions TO [public];
USE [MCDB]; GRANT SELECT ON sys.database_principal_aliases TO [public];
USE [MCDB]; GRANT SELECT ON sys.database_principals TO [public];
USE [MCDB]; GRANT SELECT ON sys.database_role_members TO [public];
USE [MCDB]; GRANT SELECT ON sys.default_constraints TO [public];
USE [MCDB]; GRANT SELECT ON sys.destination_data_spaces TO [public];
USE [MCDB]; GRANT SELECT ON sys.event_notifications TO [public];
USE [MCDB]; GRANT SELECT ON sys.events TO [public];
USE [MCDB]; GRANT SELECT ON sys.extended_procedures TO [public];
USE [MCDB]; GRANT SELECT ON sys.extended_properties TO [public];
USE [MCDB]; GRANT SELECT ON sys.filegroups TO [public];
USE [MCDB]; GRANT SELECT ON sys.foreign_key_columns TO [public];
USE [MCDB]; GRANT SELECT ON sys.foreign_keys TO [public];
USE [MCDB]; GRANT SELECT ON sys.fulltext_catalogs TO [public];
USE [MCDB]; GRANT SELECT ON sys.fulltext_index_catalog_usages TO [public];
USE [MCDB]; GRANT SELECT ON sys.fulltext_index_columns TO [public];
USE [MCDB]; GRANT SELECT ON sys.fulltext_indexes TO [public];
USE [MCDB]; GRANT SELECT ON sys.identity_columns TO [public];
USE [MCDB]; GRANT SELECT ON sys.index_columns TO [public];
USE [MCDB]; GRANT SELECT ON sys.indexes TO [public];
USE [MCDB]; GRANT SELECT ON sys.internal_tables TO [public];
USE [MCDB]; GRANT SELECT ON sys.key_constraints TO [public];
USE [MCDB]; GRANT SELECT ON sys.key_encryptions TO [public];
USE [MCDB]; GRANT SELECT ON sys.message_type_xml_schema_collection_usages TO [public];
USE [MCDB]; GRANT SELECT ON sys.module_assembly_usages TO [public];
USE [MCDB]; GRANT SELECT ON sys.numbered_procedure_parameters TO [public];
USE [MCDB]; GRANT SELECT ON sys.numbered_procedures TO [public];
USE [MCDB]; GRANT SELECT ON sys.objects TO [public];
USE [MCDB]; GRANT SELECT ON sys.parameter_type_usages TO [public];
USE [MCDB]; GRANT SELECT ON sys.parameter_xml_schema_collection_usages TO [public];
USE [MCDB]; GRANT SELECT ON sys.parameters TO [public];
USE [MCDB]; GRANT SELECT ON sys.partition_functions TO [public];
USE [MCDB]; GRANT SELECT ON sys.partition_parameters TO [public];
USE [MCDB]; GRANT SELECT ON sys.partition_range_values TO [public];
USE [MCDB]; GRANT SELECT ON sys.partition_schemes TO [public];
USE [MCDB]; GRANT SELECT ON sys.partitions TO [public];
USE [MCDB]; GRANT SELECT ON sys.plan_guides TO [public];
USE [MCDB]; GRANT SELECT ON sys.procedures TO [public];
USE [MCDB]; GRANT SELECT ON sys.remote_service_bindings TO [public];
USE [MCDB]; GRANT SELECT ON sys.routes TO [public];
USE [MCDB]; GRANT SELECT ON sys.schemas TO [public];
USE [MCDB]; GRANT SELECT ON sys.service_contract_message_usages TO [public];
USE [MCDB]; GRANT SELECT ON sys.service_contract_usages TO [public];
USE [MCDB]; GRANT SELECT ON sys.service_contracts TO [public];
USE [MCDB]; GRANT SELECT ON sys.service_message_types TO [public];
USE [MCDB]; GRANT SELECT ON sys.service_queue_usages TO [public];
USE [MCDB]; GRANT SELECT ON sys.service_queues TO [public];
USE [MCDB]; GRANT SELECT ON sys.services TO [public];
USE [MCDB]; GRANT SELECT ON sys.sql_dependencies TO [public];
USE [MCDB]; GRANT SELECT ON sys.sql_modules TO [public];
USE [MCDB]; GRANT SELECT ON sys.stats TO [public];
USE [MCDB]; GRANT SELECT ON sys.stats_columns TO [public];
USE [MCDB]; GRANT SELECT ON sys.symmetric_keys TO [public];
USE [MCDB]; GRANT SELECT ON sys.synonyms TO [public];
USE [MCDB]; GRANT SELECT ON sys.syscolumns TO [public];
USE [MCDB]; GRANT SELECT ON sys.syscomments TO [public];
USE [MCDB]; GRANT SELECT ON sys.sysconstraints TO [public];
USE [MCDB]; GRANT SELECT ON sys.sysdepends TO [public];
USE [MCDB]; GRANT SELECT ON sys.sysfilegroups TO [public];
USE [MCDB]; GRANT SELECT ON sys.sysfiles TO [public];
USE [MCDB]; GRANT SELECT ON sys.sysforeignkeys TO [public];
USE [MCDB]; GRANT SELECT ON sys.sysfulltextcatalogs TO [public];
USE [MCDB]; GRANT SELECT ON sys.sysindexes TO [public];
USE [MCDB]; GRANT SELECT ON sys.sysindexkeys TO [public];
USE [MCDB]; GRANT SELECT ON sys.sysmembers TO [public];
USE [MCDB]; GRANT SELECT ON sys.sysobjects TO [public];
USE [MCDB]; GRANT SELECT ON sys.syspermissions TO [public];
USE [MCDB]; GRANT SELECT ON sys.sysprotects TO [public];
USE [MCDB]; GRANT SELECT ON sys.sysreferences TO [public];
USE [MCDB]; GRANT SELECT ON sys.syssegments TO [public];
USE [MCDB]; GRANT SELECT ON sys.system_columns TO [public];
USE [MCDB]; GRANT SELECT ON sys.system_objects TO [public];
USE [MCDB]; GRANT SELECT ON sys.system_parameters TO [public];
USE [MCDB]; GRANT SELECT ON sys.system_sql_modules TO [public];
USE [MCDB]; GRANT SELECT ON sys.system_views TO [public];
USE [MCDB]; GRANT SELECT ON sys.systypes TO [public];
USE [MCDB]; GRANT SELECT ON sys.sysusers TO [public];
USE [MCDB]; GRANT SELECT ON sys.tables TO [public];
USE [MCDB]; GRANT SELECT ON sys.transmission_queue TO [public];
USE [MCDB]; GRANT SELECT ON sys.trigger_events TO [public];
USE [MCDB]; GRANT SELECT ON sys.triggers TO [public];
USE [MCDB]; GRANT SELECT ON sys.type_assembly_usages TO [public];
USE [MCDB]; GRANT SELECT ON sys.types TO [public];
USE [MCDB]; GRANT SELECT ON sys.views TO [public];
USE [MCDB]; GRANT SELECT ON sys.xml_indexes TO [public];
USE [MCDB]; GRANT SELECT ON sys.xml_schema_attributes TO [public];
USE [MCDB]; GRANT SELECT ON sys.xml_schema_collections TO [public];
USE [MCDB]; GRANT SELECT ON sys.xml_schema_component_placements TO [public];
USE [MCDB]; GRANT SELECT ON sys.xml_schema_components TO [public];
USE [MCDB]; GRANT SELECT ON sys.xml_schema_elements TO [public];
USE [MCDB]; GRANT SELECT ON sys.xml_schema_facets TO [public];
USE [MCDB]; GRANT SELECT ON sys.xml_schema_model_groups TO [public];
USE [MCDB]; GRANT SELECT ON sys.xml_schema_namespaces TO [public];
USE [MCDB]; GRANT SELECT ON sys.xml_schema_types TO [public];
USE [MCDB]; GRANT SELECT ON sys.xml_schema_wildcard_namespaces TO [public];
USE [MCDB]; GRANT SELECT ON sys.xml_schema_wildcards TO [public];
USE [MCDB]; GRANT VIEW DEFINITION TO [AMSA\SQL_STA_Reader];
------------------------------------------------------------------------------------------------------------

USE [MCDBStaging]; CREATE USER [AMSA\SAS Server Users] FROM LOGIN [AMSA\SAS Server Users];
USE [MCDBStaging]; CREATE USER [AMSA\SQL_STA_Reader] FROM LOGIN [AMSA\SQL_STA_Reader];
USE [MCDBStaging]; CREATE USER [amsa\svprodsqlagentexec] FROM LOGIN [amsa\svprodsqlagentexec] WITH DEFAULT_SCHEMA = [dbo];
USE [MCDBStaging]; CREATE USER [AMSA\SvProdSQLDBExec] FROM LOGIN [AMSA\SvProdSQLDBExec] WITH DEFAULT_SCHEMA = [dbo];
USE [MCDBStaging]; CREATE USER [AMSA\svstasqlagentexec] FROM LOGIN [AMSA\svstasqlagentexec] WITH DEFAULT_SCHEMA = [dbo];
USE [MCDBStaging]; CREATE USER [DBTKUser] FOR LOGIN [DBTKUser] WITH DEFAULT_SCHEMA = [dbo];
USE [MCDBStaging]; CREATE USER [teamworks] FOR LOGIN [teamworks] WITH DEFAULT_SCHEMA = [dbo];

--
--
EXEC dbo.sp_addsrvrolemember 'AMSA\SQL Cluster STA Server Service Group', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\SQL Cluster STA Agent Service Group', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\ProdDBA', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\DLake', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\TTrent', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svStaWinCluster', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svstasqlagentexec', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svstafileutility', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svstasqldbexec', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'DBTKUser', 'bulkadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svstafileutility', 'bulkadmin';
EXEC [MCDBStaging].dbo.sp_addrolemember 'db_owner', 'DBTKUser';
EXEC [MCDBStaging].dbo.sp_addrolemember 'db_owner', 'teamworks';
EXEC [MCDBStaging].dbo.sp_addrolemember 'db_owner', 'amsa\svprodsqlagentexec';
EXEC [MCDBStaging].dbo.sp_addrolemember 'db_owner', 'AMSA\SvProdSQLDBExec';
EXEC [MCDBStaging].dbo.sp_addrolemember 'db_owner', 'AMSA\svstasqlagentexec';
EXEC [MCDBStaging].dbo.sp_addrolemember 'db_datareader', 'AMSA\SAS Server Users';
EXEC [MCDBStaging].dbo.sp_addrolemember 'db_datareader', 'teamworks';
EXEC [MCDBStaging].dbo.sp_addrolemember 'db_datareader', 'AMSA\SQL_STA_Reader';
EXEC [MCDBStaging].dbo.sp_addrolemember 'db_datawriter', 'teamworks';

USE master; GRANT ADMINISTER BULK OPERATIONS TO [AMSA\svstafileutility];
USE master; GRANT ADMINISTER BULK OPERATIONS TO [DBTKUser];
USE master; GRANT ADMINISTER BULK OPERATIONS TO [teamworks];
--
USE master; GRANT CONNECT SQL TO [AMSA\bdanrel];
USE master; GRANT CONNECT SQL TO [AMSA\DLake];
USE master; GRANT CONNECT SQL TO [AMSA\estorey];
USE master; GRANT CONNECT SQL TO [AMSA\mamante];
USE master; GRANT CONNECT SQL TO [AMSA\ProdDBA];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Agent Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Full Text Search Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Server Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_STA_Reader];
USE master; GRANT CONNECT SQL TO [AMSA\SSRSReportViewer];
USE master; GRANT CONNECT SQL TO [AMSA\svstafileutility];
USE master; GRANT CONNECT SQL TO [AMSA\svstasqlagentexec];
USE master; GRANT CONNECT SQL TO [AMSA\svstasqldbexec];
USE master; GRANT CONNECT SQL TO [AMSA\SvStaSSRSExec];
USE master; GRANT CONNECT SQL TO [AMSA\svStaWinCluster];
USE master; GRANT CONNECT SQL TO [AMSA\TTrent];
--
USE master; GRANT CONNECT SQL TO [DBTKUser];
USE master; GRANT CONNECT SQL TO [NT AUTHORITY\SYSTEM];
USE master; GRANT CONNECT SQL TO [SvStaMonOSS];
USE master; GRANT CONNECT SQL TO [teamworks];
USE master; GRANT VIEW ANY DATABASE TO [public];
USE [MCDBStaging]; GRANT ALTER ON SCHEMA::dbo TO [DBTKUser];
USE [MCDBStaging]; GRANT CONNECT TO [AMSA\SAS Server Users];
USE [MCDBStaging]; GRANT CONNECT TO [AMSA\SQL_STA_Reader];
USE [MCDBStaging]; GRANT CONNECT TO [amsa\svprodsqlagentexec];
USE [MCDBStaging]; GRANT CONNECT TO [AMSA\SvProdSQLDBExec];
USE [MCDBStaging]; GRANT CONNECT TO [AMSA\svstasqlagentexec];
--
USE [MCDBStaging]; GRANT CONNECT TO [DBTKUser];
USE [MCDBStaging]; GRANT CONNECT TO [teamworks];
USE [MCDBStaging]; GRANT CONTROL ON SCHEMA::dbo TO [DBTKUser];
USE [MCDBStaging]; GRANT CREATE DEFAULT TO [DBTKUser];
USE [MCDBStaging]; GRANT CREATE FUNCTION TO [DBTKUser];
USE [MCDBStaging]; GRANT CREATE PROCEDURE TO [DBTKUser];
USE [MCDBStaging]; GRANT CREATE ROLE TO [DBTKUser];
USE [MCDBStaging]; GRANT CREATE RULE TO [DBTKUser];
USE [MCDBStaging]; GRANT CREATE SCHEMA TO [DBTKUser];
USE [MCDBStaging]; GRANT CREATE TABLE TO [DBTKUser];
USE [MCDBStaging]; GRANT CREATE TYPE TO [DBTKUser];
USE [MCDBStaging]; GRANT CREATE VIEW TO [DBTKUser];
USE [MCDBStaging]; GRANT DELETE ON SCHEMA::dbo TO [DBTKUser];
USE [MCDBStaging]; GRANT EXECUTE ON SCHEMA::dbo TO [DBTKUser];
USE [MCDBStaging]; GRANT INSERT ON SCHEMA::dbo TO [DBTKUser];
USE [MCDBStaging]; GRANT SELECT ON SCHEMA::dbo TO [DBTKUser];
USE [MCDBStaging]; GRANT SELECT ON sys.all_columns TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.all_objects TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.all_parameters TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.all_sql_modules TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.all_views TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.allocation_units TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.assemblies TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.assembly_files TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.assembly_modules TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.assembly_references TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.assembly_types TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.asymmetric_keys TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.certificates TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.check_constraints TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.column_type_usages TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.column_xml_schema_collection_usages TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.columns TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.computed_columns TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.conversation_endpoints TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.conversation_groups TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.crypt_properties TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.data_spaces TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.database_files TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.database_permissions TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.database_principal_aliases TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.database_principals TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.database_role_members TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.default_constraints TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.destination_data_spaces TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.event_notifications TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.events TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.extended_procedures TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.extended_properties TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.filegroups TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.foreign_key_columns TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.foreign_keys TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.fulltext_catalogs TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.fulltext_index_catalog_usages TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.fulltext_index_columns TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.fulltext_indexes TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.identity_columns TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.index_columns TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.indexes TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.internal_tables TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.key_constraints TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.key_encryptions TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.message_type_xml_schema_collection_usages TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.module_assembly_usages TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.numbered_procedure_parameters TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.numbered_procedures TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.objects TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.parameter_type_usages TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.parameter_xml_schema_collection_usages TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.parameters TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.partition_functions TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.partition_parameters TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.partition_range_values TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.partition_schemes TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.partitions TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.plan_guides TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.procedures TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.remote_service_bindings TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.routes TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.schemas TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.service_contract_message_usages TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.service_contract_usages TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.service_contracts TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.service_message_types TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.service_queue_usages TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.service_queues TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.services TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.sql_dependencies TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.sql_modules TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.stats TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.stats_columns TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.symmetric_keys TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.synonyms TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.syscolumns TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.syscomments TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.sysconstraints TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.sysdepends TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.sysfilegroups TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.sysfiles TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.sysforeignkeys TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.sysfulltextcatalogs TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.sysindexes TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.sysindexkeys TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.sysmembers TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.sysobjects TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.syspermissions TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.sysprotects TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.sysreferences TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.syssegments TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.system_columns TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.system_objects TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.system_parameters TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.system_sql_modules TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.system_views TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.systypes TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.sysusers TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.tables TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.transmission_queue TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.trigger_events TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.triggers TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.type_assembly_usages TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.types TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.views TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.xml_indexes TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.xml_schema_attributes TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.xml_schema_collections TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.xml_schema_component_placements TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.xml_schema_components TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.xml_schema_elements TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.xml_schema_facets TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.xml_schema_model_groups TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.xml_schema_namespaces TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.xml_schema_types TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.xml_schema_wildcard_namespaces TO [public];
USE [MCDBStaging]; GRANT SELECT ON sys.xml_schema_wildcards TO [public];
USE [MCDBStaging]; GRANT UPDATE ON SCHEMA::dbo TO [DBTKUser];
USE [MCDBStaging]; GRANT VIEW DEFINITION TO [AMSA\SQL_STA_Reader];
USE [MCDBStaging]; GRANT VIEW DEFINITION TO [DBTKUser];

--------------------------------------------------------------------------------------------------------------

USE [ODSSTAGING]; CREATE USER [AMSA\SQL_STA_Reader] FROM LOGIN [AMSA\SQL_STA_Reader];
USE [ODSSTAGING]; CREATE USER [amsa\svprodsqlagentexec] FROM LOGIN [amsa\svprodsqlagentexec] WITH DEFAULT_SCHEMA = [dbo];
USE [ODSSTAGING]; CREATE USER [AMSA\svstasqlagentexec] FROM LOGIN [AMSA\svstasqlagentexec] WITH DEFAULT_SCHEMA = [dbo];
USE [ODSSTAGING]; CREATE USER [DBTKUser] FOR LOGIN [DBTKUser] WITH DEFAULT_SCHEMA = [dbo];

--
--
EXEC dbo.sp_addsrvrolemember 'AMSA\SQL Cluster STA Server Service Group', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\SQL Cluster STA Agent Service Group', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\ProdDBA', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\DLake', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\TTrent', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svStaWinCluster', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svstasqlagentexec', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svstafileutility', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svstasqldbexec', 'sysadmin';
EXEC dbo.sp_addsrvrolemember 'DBTKUser', 'bulkadmin';
EXEC dbo.sp_addsrvrolemember 'AMSA\svstafileutility', 'bulkadmin';
EXEC [ODSSTAGING].dbo.sp_addrolemember 'db_owner', 'amsa\svprodsqlagentexec';
EXEC [ODSSTAGING].dbo.sp_addrolemember 'db_owner', 'AMSA\svstasqlagentexec';
EXEC [ODSSTAGING].dbo.sp_addrolemember 'db_datareader', 'DBTKUser';
EXEC [ODSSTAGING].dbo.sp_addrolemember 'db_datareader', 'AMSA\SQL_STA_Reader';

USE master; GRANT ADMINISTER BULK OPERATIONS TO [AMSA\svstafileutility];
USE master; GRANT ADMINISTER BULK OPERATIONS TO [DBTKUser];
USE master; GRANT ADMINISTER BULK OPERATIONS TO [teamworks];
--
USE master; GRANT CONNECT SQL TO [AMSA\bdanrel];
USE master; GRANT CONNECT SQL TO [AMSA\DLake];
USE master; GRANT CONNECT SQL TO [AMSA\estorey];
USE master; GRANT CONNECT SQL TO [AMSA\mamante];
USE master; GRANT CONNECT SQL TO [AMSA\ProdDBA];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Agent Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Full Text Search Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\SQL Cluster STA Server Service Group];
USE master; GRANT CONNECT SQL TO [AMSA\SQL_STA_Reader];
USE master; GRANT CONNECT SQL TO [AMSA\SSRSReportViewer];
USE master; GRANT CONNECT SQL TO [AMSA\svstafileutility];
USE master; GRANT CONNECT SQL TO [AMSA\svstasqlagentexec];
USE master; GRANT CONNECT SQL TO [AMSA\svstasqldbexec];
USE master; GRANT CONNECT SQL TO [AMSA\SvStaSSRSExec];
USE master; GRANT CONNECT SQL TO [AMSA\svStaWinCluster];
USE master; GRANT CONNECT SQL TO [AMSA\TTrent];
--
USE master; GRANT CONNECT SQL TO [DBTKUser];
USE master; GRANT CONNECT SQL TO [NT AUTHORITY\SYSTEM];
USE master; GRANT CONNECT SQL TO [SvStaMonOSS];
USE master; GRANT CONNECT SQL TO [teamworks];
USE master; GRANT VIEW ANY DATABASE TO [public];
USE [ODSSTAGING]; DENY EXECUTE ON dbo.fn_diagramobjects TO [guest];
USE [ODSSTAGING]; DENY EXECUTE ON dbo.sp_alterdiagram TO [guest];
USE [ODSSTAGING]; DENY EXECUTE ON dbo.sp_creatediagram TO [guest];
USE [ODSSTAGING]; DENY EXECUTE ON dbo.sp_dropdiagram TO [guest];
USE [ODSSTAGING]; DENY EXECUTE ON dbo.sp_helpdiagramdefinition TO [guest];
USE [ODSSTAGING]; DENY EXECUTE ON dbo.sp_helpdiagrams TO [guest];
USE [ODSSTAGING]; DENY EXECUTE ON dbo.sp_renamediagram TO [guest];
USE [ODSSTAGING]; GRANT CONNECT TO [AMSA\SQL_STA_Reader];
USE [ODSSTAGING]; GRANT CONNECT TO [amsa\svprodsqlagentexec];
USE [ODSSTAGING]; GRANT CONNECT TO [AMSA\svstasqlagentexec];
--
USE [ODSSTAGING]; GRANT CONNECT TO [DBTKUser];
USE [ODSSTAGING]; GRANT EXECUTE ON dbo.fn_diagramobjects TO [public];
USE [ODSSTAGING]; GRANT EXECUTE ON dbo.sp_alterdiagram TO [public];
USE [ODSSTAGING]; GRANT EXECUTE ON dbo.sp_creatediagram TO [public];
USE [ODSSTAGING]; GRANT EXECUTE ON dbo.sp_dropdiagram TO [public];
USE [ODSSTAGING]; GRANT EXECUTE ON dbo.sp_helpdiagramdefinition TO [public];
USE [ODSSTAGING]; GRANT EXECUTE ON dbo.sp_helpdiagrams TO [public];
USE [ODSSTAGING]; GRANT EXECUTE ON dbo.sp_renamediagram TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.all_columns TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.all_objects TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.all_parameters TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.all_sql_modules TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.all_views TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.allocation_units TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.assemblies TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.assembly_files TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.assembly_modules TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.assembly_references TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.assembly_types TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.asymmetric_keys TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.certificates TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.check_constraints TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.column_type_usages TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.column_xml_schema_collection_usages TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.columns TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.computed_columns TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.conversation_endpoints TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.conversation_groups TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.crypt_properties TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.data_spaces TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.database_files TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.database_permissions TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.database_principal_aliases TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.database_principals TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.database_role_members TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.default_constraints TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.destination_data_spaces TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.event_notifications TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.events TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.extended_procedures TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.extended_properties TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.filegroups TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.foreign_key_columns TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.foreign_keys TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.fulltext_catalogs TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.fulltext_index_catalog_usages TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.fulltext_index_columns TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.fulltext_indexes TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.identity_columns TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.index_columns TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.indexes TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.internal_tables TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.key_constraints TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.key_encryptions TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.message_type_xml_schema_collection_usages TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.module_assembly_usages TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.numbered_procedure_parameters TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.numbered_procedures TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.objects TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.parameter_type_usages TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.parameter_xml_schema_collection_usages TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.parameters TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.partition_functions TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.partition_parameters TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.partition_range_values TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.partition_schemes TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.partitions TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.plan_guides TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.procedures TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.remote_service_bindings TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.routes TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.schemas TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.service_contract_message_usages TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.service_contract_usages TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.service_contracts TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.service_message_types TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.service_queue_usages TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.service_queues TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.services TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.sql_dependencies TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.sql_modules TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.stats TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.stats_columns TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.symmetric_keys TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.synonyms TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.syscolumns TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.syscomments TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.sysconstraints TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.sysdepends TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.sysfilegroups TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.sysfiles TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.sysforeignkeys TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.sysfulltextcatalogs TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.sysindexes TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.sysindexkeys TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.sysmembers TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.sysobjects TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.syspermissions TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.sysprotects TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.sysreferences TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.syssegments TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.system_columns TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.system_objects TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.system_parameters TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.system_sql_modules TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.system_views TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.systypes TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.sysusers TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.tables TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.transmission_queue TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.trigger_events TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.triggers TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.type_assembly_usages TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.types TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.views TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.xml_indexes TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.xml_schema_attributes TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.xml_schema_collections TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.xml_schema_component_placements TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.xml_schema_components TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.xml_schema_elements TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.xml_schema_facets TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.xml_schema_model_groups TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.xml_schema_namespaces TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.xml_schema_types TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.xml_schema_wildcard_namespaces TO [public];
USE [ODSSTAGING]; GRANT SELECT ON sys.xml_schema_wildcards TO [public];
USE [ODSSTAGING]; GRANT VIEW DEFINITION TO [AMSA\SQL_STA_Reader];