--
-- Data extracted from SQLDEVEDM on Jul 21 2015 11:10AM
--
 
USE [EDM_AUDIT]; GRANT CONNECT TO [dbo];
USE [EDM_AUDIT]; GRANT CONNECT TO [PIMCO\edm-admin-np];
USE [EDM_AUDIT]; GRANT CONNECT TO [PIMCO\edm-read-np];
USE [EDM_AUDIT]; GRANT CONNECT TO [PIMCO\edm-write-np];
USE [EDM_AUDIT]; GRANT CONNECT TO [PIMCO\svc_refdtd];
USE [EDM_AUDIT]; GRANT CONNECT TO [svc_edmaud_dev];
USE [EDM_AUDIT]; GRANT DELETE ON SCHEMA::dbo TO [EDM_AUDIT_WR_ROLE];
USE [EDM_AUDIT]; GRANT INSERT ON SCHEMA::dbo TO [EDM_AUDIT_WR_ROLE];
USE [EDM_AUDIT]; GRANT SELECT ON SCHEMA::dbo TO [EDM_AUDIT_RO_ROLE];
USE [EDM_AUDIT]; GRANT SELECT ON SCHEMA::dbo TO [EDM_AUDIT_WR_ROLE];
USE [EDM_AUDIT]; GRANT SELECT ON sys.all_columns TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.all_objects TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.all_parameters TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.all_sql_modules TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.all_views TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.allocation_units TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.assemblies TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.assembly_files TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.assembly_modules TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.assembly_references TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.assembly_types TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.asymmetric_keys TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.certificates TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.change_tracking_tables TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.check_constraints TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.column_store_dictionaries TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.column_store_segments TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.column_type_usages TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.column_xml_schema_collection_usages TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.columns TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.computed_columns TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.conversation_endpoints TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.conversation_groups TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.conversation_priorities TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.crypt_properties TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.data_spaces TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.database_audit_specification_details TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.database_audit_specifications TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.database_files TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.database_permissions TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.database_principals TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.database_role_members TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.default_constraints TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.destination_data_spaces TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.event_notifications TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.events TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.extended_procedures TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.extended_properties TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.filegroups TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.filetable_system_defined_objects TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.filetables TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.foreign_key_columns TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.foreign_keys TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.fulltext_catalogs TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.fulltext_index_catalog_usages TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.fulltext_index_columns TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.fulltext_index_fragments TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.fulltext_indexes TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.fulltext_stoplists TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.fulltext_stopwords TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.function_order_columns TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.identity_columns TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.index_columns TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.indexes TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.internal_tables TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.key_constraints TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.key_encryptions TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.message_type_xml_schema_collection_usages TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.module_assembly_usages TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.numbered_procedure_parameters TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.numbered_procedures TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.objects TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.parameter_type_usages TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.parameter_xml_schema_collection_usages TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.parameters TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.partition_functions TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.partition_parameters TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.partition_range_values TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.partition_schemes TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.partitions TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.plan_guides TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.procedures TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.registered_search_properties TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.registered_search_property_lists TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.remote_service_bindings TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.routes TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.schemas TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.selective_xml_index_namespaces TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.selective_xml_index_paths TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.sequences TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.service_contract_message_usages TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.service_contract_usages TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.service_contracts TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.service_message_types TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.service_queue_usages TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.service_queues TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.services TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.spatial_index_tessellations TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.spatial_indexes TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.sql_dependencies TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.sql_modules TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.stats TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.stats_columns TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.symmetric_keys TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.synonyms TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.syscolumns TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.syscomments TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.sysconstraints TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.sysdepends TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.sysfilegroups TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.sysfiles TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.sysforeignkeys TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.sysfulltextcatalogs TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.sysindexes TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.sysindexkeys TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.sysmembers TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.sysobjects TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.syspermissions TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.sysprotects TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.sysreferences TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.system_columns TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.system_objects TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.system_parameters TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.system_sql_modules TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.system_views TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.systypes TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.sysusers TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.table_types TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.tables TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.transmission_queue TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.trigger_events TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.triggers TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.type_assembly_usages TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.types TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.views TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.xml_indexes TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.xml_schema_attributes TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.xml_schema_collections TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.xml_schema_component_placements TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.xml_schema_components TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.xml_schema_elements TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.xml_schema_facets TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.xml_schema_model_groups TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.xml_schema_namespaces TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.xml_schema_types TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.xml_schema_wildcard_namespaces TO [public];
USE [EDM_AUDIT]; GRANT SELECT ON sys.xml_schema_wildcards TO [public];
USE [EDM_AUDIT]; GRANT UPDATE ON SCHEMA::dbo TO [EDM_AUDIT_WR_ROLE];
USE master; GRANT ADMINISTER BULK OPERATIONS TO [PIMCO\edm-read-np];
USE master; GRANT ADMINISTER BULK OPERATIONS TO [PIMCO\edm-write-np];
USE master; GRANT ALTER ANY AVAILABILITY GROUP TO [NT AUTHORITY\SYSTEM];
USE master; GRANT ALTER TRACE TO [PIMCO\edm-read-np];
USE master; GRANT ALTER TRACE TO [PIMCO\edm-write-np];
USE master; GRANT CONNECT TO [public];
USE master; GRANT CONNECT SQL TO [##MS_PolicyEventProcessingLogin##];
USE master; GRANT CONNECT SQL TO [##MS_PolicyTsqlExecutionLogin##];
USE master; GRANT CONNECT SQL TO [dpa];
USE master; GRANT CONNECT SQL TO [IMSWEST\IA Database Admins];
USE master; GRANT CONNECT SQL TO [NT AUTHORITY\SYSTEM];
USE master; GRANT CONNECT SQL TO [NT Service\MSSQLSERVER];
USE master; GRANT CONNECT SQL TO [NT SERVICE\SQLSERVERAGENT];
USE master; GRANT CONNECT SQL TO [NT SERVICE\SQLWriter];
USE master; GRANT CONNECT SQL TO [NT SERVICE\Winmgmt];
USE master; GRANT CONNECT SQL TO [PIMCO\edm-admin-np];
USE master; GRANT CONNECT SQL TO [PIMCO\edm-biz-read];
USE master; GRANT CONNECT SQL TO [PIMCO\EDM-BIZ-Write];
USE master; GRANT CONNECT SQL TO [PIMCO\edm-qa-np];
USE master; GRANT CONNECT SQL TO [PIMCO\edm-read-np];
USE master; GRANT CONNECT SQL TO [PIMCO\edm-write-np];
USE master; GRANT CONNECT SQL TO [PIMCO\iis-admin];
USE master; GRANT CONNECT SQL TO [PIMCO\svc_PIMCOCM];
USE master; GRANT CONNECT SQL TO [PIMCO\svc_refdtd];
USE master; GRANT CONNECT SQL TO [PIMCO\Technology - Services DBA];
USE master; GRANT CONNECT SQL TO [sa];
USE master; GRANT CONNECT SQL TO [svc_edm_ver_dev ];
USE master; GRANT CONNECT SQL TO [svc_edmaud_dev];
USE master; GRANT VIEW ANY DATABASE TO [public];
USE master; GRANT VIEW ANY DEFINITION TO [##MS_PolicyTsqlExecutionLogin##];
USE master; GRANT VIEW SERVER STATE TO [##MS_PolicyTsqlExecutionLogin##];
USE master; GRANT VIEW SERVER STATE TO [NT AUTHORITY\SYSTEM];
USE master; GRANT VIEW SERVER STATE TO [PIMCO\edm-admin-np];
USE master; GRANT VIEW SERVER STATE TO [PIMCO\edm-read-np];
USE master; GRANT VIEW SERVER STATE TO [PIMCO\edm-write-np];
